var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var moment = require('moment');
var Promise = require('bluebird');
var _ = require('underscore');

var codeList = [
  { code: '0000',     cname: '市場別', ename: 'Market', category: 'Z' },
  { code: '0002',     cname: '財報類別(1個別2個體3合併)',     ename: 'Financial Report Type (1.Individual 2. Parent Company Only 3.Consolidated)',     category: 'Z' },
  { code: '0003',     cname: '財報發布日',     ename: 'Date of preparation of financial statements',     category: 'Z' },
  { code: '0004',     cname: '財報年月起日',     ename: 'Fiscal Year Start Date',     category: 'Z' },
  { code: '0005',     cname: '財報年月迄日',     ename: 'Fiscal Year End Date',     category: 'Z' },
  { code: '0010',     cname: '資產總額',     ename: 'Total assets',     category: 'A' },
  { code: '0020',     cname: '負債及股東權益總額',     ename: 'Total Liabilities & Equity',     category: 'A' },
  { code: '0100',     cname: '流動資產',     ename: 'Total current assets',     category: 'A' },
  { code: '0112',     cname: '現金及約當現金',     ename: 'Total cash and cash equivalents',     category: 'A' },
  { code: '0119',     cname: '附賣回債券投資',     ename: 'Bond investments under resale agreements',     category: 'A' },
  { code: '011A',     cname: '附賣回票券投資',     ename: 'Bill investments under resale agreements',     category: 'A' },
  { code: '012C',     cname: '透過損益按公允價值衡量之金融資產─流動',     ename: 'Total current financial assets at fair value through profit or loss',     category: 'A' },
  { code: '012H',     cname: '備供出售金融資產─流動',     ename: 'Financial Assets Available-for-Sale - Current',     category: 'A' },
  { code: '012K',     cname: '持有至到期日金融資產─流動',     ename: 'Held-To-Maturity Financial Assets - Current',     category: 'A' },
  { code: '012M',     cname: '避險之衍生金融資產─流動',     ename: 'Current derivative financial assets for hedging',     category: 'A' },
  { code: '012N',     cname: '以成本衡量之金融資產─流動',     ename: 'Current financial assets at cost, net',     category: 'A' },
  { code: '012P',     cname: '無活絡市場之債券投資─流動',     ename: 'Current bond investment without active market, net',     category: 'A' },
  { code: '012R',     cname: '附賣回票券及債券投資',     ename: 'Securities purchased under resell agreements, net',     category: 'A' },
  { code: '0130',     cname: '應收帳款及票據',     ename: 'Accounts & Notes Receivable',     category: 'A' },
  { code: '013D',     cname: '應收保費',     ename: 'Premiums receivable, net',     category: 'A' },
  { code: '0140',     cname: '應收代理店款',     ename: 'Agency current-debit (for sea/land shipping business)',     category: 'A' },
  { code: '0146',     cname: '存放及拆放同業',     ename: 'Total due from the central bank and call loans to banks',     category: 'A' },
  { code: '0157',     cname: '轉融通保證金',     ename: 'Refinancing margin',     category: 'A' },
  { code: '0160',     cname: '其他應收款',     ename: 'Other Receivable',     category: 'A' },
  { code: '0162',     cname: '應收轉融通擔保價款',     ename: 'Refinancing collateral receivable',     category: 'A' },
  { code: '0165',     cname: '資金貸予他人─流動',     ename: 'Loan to Others - Short-Term',     category: 'A' },
  { code: '0166',     cname: '應收證券融資款',     ename: 'Margin loans receivable',     category: 'A' },
  { code: '016A',     cname: '其他金融資產─流動',     ename: 'Other current financial assets',     category: 'A' },
  { code: '016F',     cname: '應攤回再保賠款與給付淨額',     ename: 'Claims recoverable from reinsurers, net',     category: 'A' },
  { code: '016G',     cname: '應收再保往來款項淨額',     ename: 'Due from reinsurers and ceding companies, net',     category: 'A' },
  { code: '016Z',     cname: '應收證券借貸款項',     ename: 'Total receivable of securities business money lending',     category: 'A' },
  { code: '0170',     cname: '存貨',     ename: 'Total inventories',     category: 'A' },
  { code: '017L',     cname: '生物資產流動',     ename: 'Current biological assets, net',     category: 'A' },
  { code: '017N',     cname: '生物資產非流動',     ename: 'Total non-current biological assets',     category: 'A' },
  { code: '017O',     cname: '應收款項',     ename: 'Receivables, net',     category: 'A' },
  { code: '017P',     cname: '分出未滿期保費準備淨額',     ename: 'Ceded unearned premium reserve, net',     category: 'A' },
  { code: '017Q',     cname: '分出賠款準備淨額',     ename: 'Ceded claim reserve, net',     category: 'A' },
  { code: '017R',     cname: '分出保費不足準備淨額',     ename: 'Ceded premium deficiency reserve, net',     category: 'A' },
  { code: '017S',     cname: '分出其他保險準備淨額',     ename: 'Ceded Other Reserve - net',     category: 'A' },
  { code: '017Z',     cname: '應收建造合約款',     ename: 'Construction contracts receivable',     category: 'A' },
  { code: '0180',     cname: '預付費用及預付款',     ename: 'Total prepayments',     category: 'A' },
  { code: '0182',     cname: '當期所得稅資產─流動',     ename: 'Total current tax assets',     category: 'A' },
  { code: '0184',     cname: '應收期貨交易保證金',     ename: 'Futures exchanges margins receivable',     category: 'A' },
  { code: '0187',     cname: '借券擔保價款',     ename: 'Security borrowing collateral price',     category: 'A' },
  { code: '0188',     cname: '借券保證金─存出',     ename: 'Security borrowing margin',     category: 'A' },
  { code: '0189',     cname: '違約證券',     ename: 'Securities held for customer default',     category: 'A' },
  { code: '018I',     cname: '再保險準備資產淨額',     ename: 'Reinsurance reserve assets, net',     category: 'A' },
  { code: '018L',     cname: '預付退休金─流動',     ename: 'Current prepaid pension cost',     category: 'A' },
  { code: '0190',     cname: '其他流動資產',     ename: 'Other Current Assets',     category: 'A' },
  { code: '0197',     cname: '待出售非流動資產',     ename: 'Non-current assets classified as held for sale, net',     category: 'A' },
  { code: '01AA',     cname: '分出責任準備淨額',     ename: 'Ceded liability reserve, net',     category: 'A' },
  { code: '01AB',     cname: '分出負債適足準備淨額',     ename: 'Ceded liability adequacy reserve, net',     category: 'A' },
  { code: '01AC',     cname: '再保險合約資產淨額',     ename: 'Total reinsurance assets',     category: 'A' },
  { code: '0200',     cname: '貼現及放款',     ename: 'Discounts and loans, net',     category: 'A' },
  { code: '0300',     cname: '投資淨額',     ename: 'Total investments',     category: 'A' },
  { code: '0314',     cname: '採權益法之長期股權投資',     ename: 'Investments accounted for using equity method, net',     category: 'A' },
  { code: '0315',     cname: '預付投資款',     ename: 'Non-current prepayments for investments',     category: 'A' },
  { code: '031W',     cname: '基金', ename: 'Total funds', category: 'A' },
  { code: '032A',     cname: '投資性不動產淨額',     ename: 'Investment property, net',     category: 'A' },
  { code: '032C',     cname: '特別準備金',     ename: 'Special reserve -Assets',     category: 'A' },
  { code: '0340',     cname: '透過損益按公允價值衡量之金融資產─非流動',     ename: 'Total non-current financial assets at fair value through profit or loss',     category: 'A' },
  { code: '0350',     cname: '備供出售金融資產─非流動',     ename: 'Financial Assets Available-for-Sale - Non-Current',     category: 'A' },
  { code: '0360',     cname: '持有至到期日金融資產─非流動',     ename: 'Held-to-Maturity Financial Assets - Non-Current',     category: 'A' },
  { code: '0370',     cname: '避險之衍生金融資產─非流動',     ename: 'Derivative non-current financial assets for hedging',     category: 'A' },
  { code: '0374',     cname: '受限制資產',     ename: 'Restricted assets, net',     category: 'A' },
  { code: '0380',     cname: '以成本衡量之金融資產─非流動',     ename: 'Non-current financial assets at cost, net',     category: 'A' },
  { code: '0390',     cname: '無活絡市場之債券投資─非流動',     ename: 'Non-current bond investment without active market, net',     category: 'A' },
  { code: '0395',     cname: '其他非流動資產─其他',     ename: 'Total other non-current assets -Others',     category: 'A' },
  { code: '0400',     cname: '不動產廠房及設備',     ename: 'Total property, plant and equipment',     category: 'A' },
  { code: '0810',     cname: '遞延資產合計',     ename: 'Deferred Assets',     category: 'A' },
  { code: '0813',     cname: '遞延所得稅資產',     ename: 'Deferred tax assets',     category: 'A' },
  { code: '0814',     cname: '其他遞延資產淨額',     ename: 'Other Deferred Assets',     category: 'A' },
  { code: '081A',     cname: '遞延取得成本',     ename: 'Deferred acquisition costs',     category: 'A' },
  { code: '0820',     cname: '商譽及無形資產合計',     ename: 'Goodwill And Intangible Assets',     category: 'A' },
  { code: '0821',     cname: '商譽淨額', ename: 'Goodwill', category: 'A' },
  { code: '0823',     cname: '其他無形資產淨額',     ename: 'Other Intangible Assets',     category: 'A' },
  { code: '0825',     cname: '電腦軟體成本額',     ename: 'Computer software',     category: 'A' },
  { code: '082C',     cname: '發展中之無形資產',     ename: 'Intangible assets under development, net',     category: 'A' },
  { code: '082J',     cname: '特許權',     ename: 'Franchise, net',     category: 'A' },
  { code: '0830',     cname: '員工人數',     ename: 'Number of Employees',     category: 'T' },
  { code: '0840',     cname: '其他金融資產',     ename: 'Other financial assets, net',     category: 'A' },
  { code: '0846',     cname: '長期預付租金',     ename: 'Long-term prepaid rents',     category: 'A' },
  { code: '0847',     cname: '預付設備款',     ename: 'Prepayments for business facilities',     category: 'A' },
  { code: '0890',     cname: '其他非流動資產',     ename: 'Total other non-current assets',     category: 'A' },
  { code: '089J',     cname: '分離帳戶保險商品資產',     ename: 'Assets on insurance product, separated account',     category: 'A' },
  { code: '089L',     cname: '存出保證金',     ename: 'Total guarantee deposits paid',     category: 'A' },
  { code: '089M',     cname: '存出再保責任準備金',     ename: 'Total reinsurance liability reserve contributed',     category: 'A' },
  { code: '089Q',     cname: '遞延借項─非流動',     ename: 'Deferred debits, losses on inter-affiliate accounts',     category: 'A' },
  { code: '089Y',     cname: '其他什項資產',     ename: 'Total other assets, others',     category: 'A' },
  { code: '0900',     cname: '客戶保證金專戶',     ename: 'Total customer margin account',     category: 'A' },
  { code: '0901',     cname: '國內分行家數',     ename: 'Number of Branches(Domestic)',     category: '' },
  { code: '0902',     cname: '特殊用途基金',     ename: 'Total special purpose funds',     category: 'A' },
  { code: '0903',     cname: '期貨交易人權益',     ename: 'Total futures traders\' equity',     category: 'A' },
  { code: '0960',     cname: '非流動資產',     ename: 'Total Non-Current Assets',     category: 'A' },
  { code: '1000',     cname: '負債總額',     ename: 'Total liabilities',     category: 'A' },
  { code: '1100',     cname: '流動負債',     ename: 'Total Current Liabilities',     category: 'A' },
  { code: '1110',     cname: '應付商業本票／承兌匯票',     ename: 'Total short-term notes and bills payable',     category: 'A' },
  { code: '1112',     cname: '附買回債券負債',     ename: 'Total liabilities for bonds with attached repurchase agreements',     category: 'A' },
  { code: '1116',     cname: '融券保證金',     ename: 'Securities financing refundable deposits',     category: 'A' },
  { code: '1117',     cname: '應付融券擔保價款',     ename: 'Deposits payable for securities financing',     category: 'A' },
  { code: '1118',     cname: '轉融通借入款',     ename: 'Refinancing borrowings',     category: 'A' },
  { code: '1120',     cname: '短期借款',     ename: 'Total short-term borrowings',     category: 'A' },
  { code: '1123',     cname: '透過損益按公允價值衡量之金融負債─流動',     ename: 'Total current financial liabilities at fair value through profit or loss',     category: 'A' },
  { code: '1128',     cname: '避險之衍生金融負債─流動',     ename: 'Current derivative financial liabilities for hedging',     category: 'A' },
  { code: '1129',     cname: '以成本衡量之金融負債─流動',     ename: 'Financial Liabilities Carried at Cost - Current',     category: 'A' },
  { code: '112A',     cname: '特別股負債─流動',     ename: 'Current preference share liabilities',     category: 'A' },
  { code: '112K',     cname: '附買回票券負債',     ename: 'Liabilities for bills with attached repurchase agreements',     category: 'A' },
  { code: '1130',     cname: '應付帳款及票據',     ename: 'Accounts and Notes Payable',     category: 'A' },
  { code: '1135',     cname: '應付保險賠款與給付',     ename: 'Claims payable',     category: 'A' },
  { code: '113E',     cname: '應付再保賠款與給付',     ename: 'Reinsurance indemnity payable',     category: 'A' },
  { code: '1140',     cname: '應付代理店款',     ename: 'Agency current-credit (for sea/land and shipping business)',     category: 'A' },
  { code: '1146',     cname: '央行及同業存款',     ename: 'Total deposits from the central bank and banks',     category: 'A' },
  { code: '1160',     cname: '短期債務',     ename: 'Short-term liabilities, net',     category: 'A' },
  { code: '116A',     cname: '應付商業本票',     ename: 'Commercial Paper Payable',     category: 'A' },
  { code: '116B',     cname: '附買回票債券負債',     ename: 'Total notes and bonds issued under repurchase agreement',     category: 'A' },
  { code: '1171',     cname: '應付佣金',     ename: 'Commissions payable',     category: 'A' },
  { code: '1172',     cname: '應付再保往來款',     ename: 'Due to reinsurers and ceding companies',     category: 'A' },
  { code: '117D',     cname: '應付款項',     ename: 'Total accounts payable',     category: 'A' },
  { code: '1180',     cname: '預收款項',     ename: 'Total advance receipts',     category: 'A' },
  { code: '1181',     cname: '當期所得稅負債',     ename: 'Current tax liabilities',     category: 'A' },
  { code: '118D',     cname: '應付建造合約款',     ename: 'Construction contracts payable',     category: 'A' },
  { code: '1190',     cname: '其他應付款',     ename: 'Other Payable',     category: 'A' },
  { code: '1197',     cname: '其他金融負債─流動',     ename: 'Other current financial liabilities',     category: 'A' },
  { code: '1199',     cname: '與待出售非流動資產直接相關之負債',     ename: 'Liabilities included in disposal groups classified as held for sale',     category: 'A' },
  { code: '119P',     cname: '借券保證金─存入',     ename: 'Securities lending refundable deposits',     category: 'A' },
  { code: '119Q',     cname: '代收款項',     ename: 'Total receipts under custody',     category: 'A' },
  { code: '1220',     cname: '一年內到期長期負債',     ename: 'Total long-term liabilities, current portion',     category: 'A' },
  { code: '1230',     cname: '其他流動負債',     ename: 'Other Current Liability',     category: 'A' },
  { code: '123A',     cname: '負債準備─流動',     ename: 'Total current provisions',     category: 'A' },
  { code: '1300',     cname: '存款及匯款',     ename: 'Total deposits and remittances',     category: 'A' },
  { code: '140A',     cname: '央行及同業融資',     ename: 'Total due to the central bank and banks',     category: 'A' },
  { code: '1410',     cname: '長期借款─非流動',     ename: 'Total long-term borrowings',     category: 'A' },
  { code: '1411',     cname: '銀行借款─非流動',     ename: 'Long-term bank loans',     category: 'A' },
  { code: '1420',     cname: '應付公司債 /金融債',     ename: 'Bonds & Convertible',     category: 'A' },
  { code: '1421',     cname: '應付公司債─非流動',     ename: 'Total bonds payable',     category: 'A' },
  { code: '1422',     cname: '其他借款 (長短期)',     ename: 'Total other borrowings',     category: 'A' },
  { code: '1441',     cname: '其他長期借款─非流動',     ename: 'Other Long-Term Payable',     category: 'A' },
  { code: '1444',     cname: '長期遞延收入',     ename: 'Long-term deferred revenue',     category: 'A' },
  { code: '1470',     cname: '特別股負債',     ename: 'Total preferred stock liabilities',     category: 'A' },
  { code: '1485',     cname: '特別股負債─非流動',     ename: 'Non-current preference share liabilities',     category: 'A' },
  { code: '1486',     cname: '其他金融負債─非流動',     ename: 'Total other non-current financial liabilities',     category: 'A' },
  { code: '1490',     cname: '遞延貸項',     ename: 'Deferred credits, gains on inter-affiliate accounts',     category: 'A' },
  { code: '1491',     cname: '遞延手續費收入',     ename: 'Deferred fee income',     category: 'A' },
  { code: '1500',     cname: '其他負債',     ename: 'Total other liabilities',     category: 'A' },
  { code: '1501',     cname: '存入再保責任準備金',     ename: 'Reinsurance liability reserve received',     category: 'A' },
  { code: '1510',     cname: '應計退休金負債',     ename: 'Accrued pension liabilities',     category: 'A' },
  { code: '1515',     cname: '遞延所得稅',     ename: 'Total deferred tax liabilities',     category: 'A' },
  { code: '1519',     cname: '稅額扣抵比率',     ename: 'Estimated Tax Credit Rate',     category: 'I' },
  { code: '1520',     cname: '什項負債',     ename: 'Total other liabilities',     category: 'A' },
  { code: '1522',     cname: '預計稅額扣抵比率',     ename: 'Tax1% Estimate',     category: 'I' },
  { code: '1526',     cname: '分離帳戶保險商品負債',     ename: 'Liabilities on insurance product, separated account',     category: 'A' },
  { code: '1553',     cname: '營運槓桿度',     ename: 'Degree of Operating Leverage',     category: 'Y' },
  { code: '1554',     cname: '財務槓桿度',     ename: 'Degree of Financial Leverage',     category: 'Y' },
  { code: '1560',     cname: '負債準備─非流動',     ename: 'Total non-current provisions',     category: 'A' },
  { code: '1561',     cname: '資本適足率 (以上)',     ename: 'Bank of International Settlement Ratio',     category: '' },
  { code: '1562',     cname: '資本適足率 (以下)',     ename: 'Risk-Based Capital Ratio (below)',     category: '' },
  { code: '1569',     cname: '其他負債準備',     ename: 'Other provisions',     category: 'A' },
  { code: '156E',     cname: '存入保證金',     ename: 'Guarantee deposits and margins received',     category: 'A' },
  { code: '156K',     cname: '員工福利負債準備',     ename: 'Provisions for employee benefits',     category: 'A' },
  { code: '156L',     cname: '除役負債準備',     ename: 'Provision for decommissioning, restoration and rehabilitation costs',     category: 'A' },
  { code: '156N',     cname: '員工福利-應計退休金負債',     ename: 'Accrued pension payable for employee benefits',     category: 'A' },
  { code: '1580',     cname: '透過損益按公允價值衡量之金融負債─非流動',     ename: 'Total non-current financial liabilities at fair value through profit or loss',     category: 'A' },
  { code: '1583',     cname: '避險之衍生金融負債─非流動',     ename: 'Non-current derivative financial liabilities for hedging',     category: 'A' },
  { code: '1584',     cname: '以成本衡量之金融負債─非流動',     ename: 'Financial Liabilities Carried at Cost - Non-Current',     category: 'A' },
  { code: '1590',     cname: '其他非流動負債',     ename: 'Other Non-Current Liability',     category: 'A' },
  { code: '1700',     cname: '保險負債',     ename: 'Total insurance liabilities',     category: 'A' },
  { code: '1710',     cname: '未滿期保費準備',     ename: 'Unearned premium reserve',     category: 'A' },
  { code: '1720',     cname: '責任準備',     ename: 'Liability reserve',     category: 'A' },
  { code: '1730',     cname: '特別準備',     ename: 'Special claim reserve',     category: 'A' },
  { code: '1740',     cname: '賠款準備',     ename: 'Claim reserve',     category: 'A' },
  { code: '1750',     cname: '營業損失準備',     ename: 'Reserve for operation loss',     category: 'A' },
  { code: '175A',     cname: '其他保險準備',     ename: 'Other reserves',     category: 'A' },
  { code: '1760',     cname: '保費不足準備',     ename: 'Premium insufficient reserve',     category: 'A' },
  { code: '1770',     cname: '負債適足準備',     ename: 'Liability adequacy reserve',     category: 'A' },
  { code: '1780',     cname: '保險契約準備－金融商品性質',     ename: 'Reserve for insurance with nature of financial instrument',     category: 'A' },
  { code: '1790',     cname: '外匯價格變動準備',     ename: 'Reserve for foreign exchange valuation',     category: 'A' },
  { code: '1800',     cname: '非流動負債',     ename: 'Total non-current liabilities',     category: 'A' },
  { code: '2000',     cname: '股東權益總額',     ename: 'Total equity',     category: 'A' },
  { code: '200D',     cname: '每股淨值 (F) (TSE公告數)',     ename: 'Book Value Per Share (F) (TSE)',     category: 'U' },
  { code: '200E',     cname: '母公司股東權益合計',     ename: 'Total equity attributable to owners of parent',     category: 'A' },
  { code: '2110',     cname: '普通股股本',     ename: 'Ordinary share',     category: 'A' },
  { code: '2117',     cname: '發放特別股股息',     ename: 'Preferred Stock Dividends',     category: 'B' },
  { code: '211E',     cname: '股本', ename: 'Capital', category: 'A' },
  { code: '211F',     cname: '加權平均股數 (仟股)',     ename: 'Average Commen Shares (Thousand)',     category: 'B' },
  { code: '211I',     cname: '加權平均股數─稀釋',     ename: 'Average Diluted Commen Shares (Thousand)',     category: 'B' },
  { code: '2120',     cname: '特別股股本',     ename: 'Preference share',     category: 'A' },
  { code: '2200',     cname: '預收股款',     ename: 'Advance receipts for share capital',     category: 'A' },
  { code: '2300',     cname: '待分配股票股利',     ename: 'Stock dividend to be distributed',     category: 'A' },
  { code: '2302',     cname: '換股權利證書',     ename: 'Certificate of Entitlement to New Shares',     category: 'A' },
  { code: '2310',     cname: '資本公積合計',     ename: 'Total capital surplus',     category: 'A' },
  { code: '2311',     cname: '資本公積─發行溢價',     ename: 'Total capital surplus, additional paid-in capital',     category: 'A' },
  { code: '2313',     cname: '資本公積─處分資產增益',     ename: 'Capital surplus, gain on disposals of property, plant and equipment',     category: 'A' },
  { code: '2314',     cname: '資本公積─採權益法認列關聯企業及合資企業股權淨值之變動數',     ename: 'Capital surplus, changes in equity of associates and joint ventures accounted fo',     category: 'A' },
  { code: '2315',     cname: '資本公積─受贈資產',     ename: 'Capital Reserve - Donation',     category: 'A' },
  { code: '2316',     cname: '資本公積─其他',     ename: 'Capital surplus, others',     category: 'A' },
  { code: '2317',     cname: '資本公積─庫藏股票交易',     ename: 'Capital surplus, treasury share transactions',     category: 'A' },
  { code: '2318',     cname: '資本公積─合併溢額',     ename: 'Capital surplus, net assets from merger',     category: 'A' },
  { code: '2319',     cname: '資本公積─員工認股權',     ename: 'Capital surplus, employee share options',     category: 'A' },
  { code: '231A',     cname: '資本公積─認股權',     ename: 'Capital surplus, share options',     category: 'A' },
  { code: '231K',     cname: '資本公積─處分子公司股權價格與帳面價值差額',     ename: 'Capital surplus, difference between consideration and carrying amount of subsidi',     category: 'A' },
  { code: '231L',     cname: '資本公積─限制員工權利股票',     ename: 'Capital surplus, restrict employee stock',     category: 'A' },
  { code: '2320',     cname: '法定盈餘公積',     ename: 'Legal reserve',     category: 'A' },
  { code: '2330',     cname: '特別盈餘公積',     ename: 'Special reserve',     category: 'A' },
  { code: '2340',     cname: '未分配盈餘',     ename: 'Total unappropriated retained earnings (accumulated deficit)',     category: 'A' },
  { code: '2341',     cname: '保留盈餘',     ename: 'Total retained earnings',     category: 'A' },
  { code: '2360',     cname: '國外營運機構財務報表換算之兌換差額',     ename: 'Total exchange differences on translation of foreign financial statements',     category: 'A' },
  { code: '2370',     cname: '重估增值',     ename: 'Total revaluation surplus',     category: 'A' },
  { code: '2400',     cname: '庫藏股票帳面值',     ename: 'Treasury shares',     category: 'A' },
  { code: '2402',     cname: '稅前息前淨利',     ename: 'Earnings Before Interest and Tax',     category: 'B' },
  { code: '2403',     cname: '稅前息前折舊前淨利',     ename: 'Earnings Before Interest, Tax, Depreciation and Amortization',     category: 'B' },
  { code: '240D',     cname: '庫藏股數─母公司',     ename: 'Treasury Shares-buys back',     category: 'B' },
  { code: '240E',     cname: '庫藏股數─子公司持有母公司股票或其他',     ename: 'Treasury Shares-Subsidiary Holding',     category: 'B' },
  { code: '240G',     cname: '庫藏股數 (母+ 子) 仟股',     ename: 'Total Treasury Shares',     category: 'B' },
  { code: '2420',     cname: '指撥營運資金',     ename: 'Total atssigned working capital',     category: 'A' },
  { code: '2430',     cname: '營運資金─期貨',     ename: 'Working capital-futures (re-consigned foreign futures trading business)',     category: 'A' },
  { code: '2440',     cname: '股東權益其他調整項',     ename: 'Other equity, others',     category: 'A' },
  { code: '2461',     cname: '備供出售金融資產未實現損益',     ename: 'Total unrealized gains (losses) on available-for-sale financial assets',     category: 'A' },
  { code: '2462',     cname: '現金流量避險中屬有效避險部分之避險工具損益',     ename: 'Total gains (losses) on effective portion of cash flow hedges',     category: 'A' },
  { code: '246A',     cname: '國外營運機構淨投資避險中屬有效避險部分之避險工具損益',     ename: 'Total gains (losses) on effective portion of hedges of net investments in foreig',     category: 'A' },
  { code: '2470',     cname: '與待出售非流動資產直接相關之權益',     ename: 'Total equity related to non-current assets classified as held for sale',     category: 'A' },
  { code: '2471',     cname: '其他權益--員工未賺得酬勞',     ename: 'Other equity - unearned compensation',     category: 'A' },
  { code: '2480',     cname: '其他權益',     ename: 'Total other equity interest',     category: 'A' },
  { code: '2801',     cname: '共同控制下前手權益',     ename: 'Interests in the former associate or jointly controlled entity',     category: 'A' },
  { code: '2802',     cname: '合併前非屬共同控制股權',     ename: 'Non-controlling interest in pre-acquisition share capital',     category: 'A' },
  { code: '2900',     cname: '非控制權益',     ename: 'Non-controlling interests',     category: 'A' },
  { code: '3100',     cname: '營業收入淨額',     ename: 'Total operating revenue',     category: 'B' },
  { code: '3101',     cname: '營收─處分投資收入',     ename: 'Operating Revenue - Disposal of Investments',     category: 'B' },
  { code: '3102',     cname: '營收─租金收入',     ename: 'Total rental revenue',     category: 'B' },
  { code: '3103',     cname: '營收─投資收益',     ename: 'Total investment revenue',     category: 'B' },
  { code: '3105',     cname: '營業收入毛額',     ename: 'Gross Operating Revenue',     category: 'B' },
  { code: '3107',     cname: '其他營業收益',     ename: 'Total other operating income',     category: 'B' },
  { code: '310A',     cname: '營收─處分土地收入',     ename: 'Operating Revenue - Disposal of Lands',     category: 'B' },
  { code: '310C',     cname: '收入合計',     ename: 'Total revenue',     category: 'B' },
  { code: '3112',     cname: '經紀手續費收入',     ename: 'Total brokerage handling fee revenue',     category: 'B' },
  { code: '3113',     cname: '承銷業務收入',     ename: 'Total revenues from underwriting business',     category: 'B' },
  { code: '3114',     cname: '股務代理收入',     ename: 'Revenue from providing agency service for stock affairs',     category: 'B' },
  { code: '3115',     cname: '出售證券淨利損─自營',     ename: 'Gains (losses) on sale of securities-proprietary, net',     category: 'B' },
  { code: '3116',     cname: '出售證券淨利損─承銷',     ename: 'Gains (losses) on sale of securities-underwriting, net',     category: 'B' },
  { code: '3118',     cname: '營收─利息收入',     ename: 'Interest revenue',     category: 'B' },
  { code: '3119',     cname: '股利收入─營業收入',     ename: 'Revenue from dividends',     category: 'B' },
  { code: '311B',     cname: '借貸款項手續費收入',     ename: 'Handling fee revenues from securities business money lending',     category: 'B' },
  { code: '311C',     cname: '借券收入',     ename: 'Income from securities lendings',     category: 'B' },
  { code: '311D',     cname: '應付抵繳保證金證券回補淨利益(損失)',     ename: 'Gains (losses) on covering of liabilities on securities for margin requirement,',     category: 'B' },
  { code: '311E',     cname: '應付抵繳保證金證券透過損益按公允價值衡量之淨利益(損失)',     ename: 'Valuation g/l on liabilities of securities for margin requirement at fv thro.p/l',     category: 'B' },
  { code: '311F',     cname: '出售票券淨利益(損失)',     ename: 'Gains (losses) on sale of bills, net',     category: 'B' },
  { code: '311G',     cname: '財務管理業務淨收益',     ename: 'Gains (losses) on wealth management, net',     category: 'B' },
  { code: '3129',     cname: '期貨佣金收入',     ename: 'Total future commission revenue',     category: 'B' },
  { code: '312A',     cname: '期貨管理費收入',     ename: 'Total futures administrative fee revenues',     category: 'B' },
  { code: '312B',     cname: '經理費收入',     ename: 'Total management fee revenues',     category: 'B' },
  { code: '312C',     cname: '證券佣金收入',     ename: 'Total security commission revenue',     category: 'B' },
  { code: '312M',     cname: '衍生性金融商品淨損益─櫃檯─換利淨利益(損失)',     ename: 'Gain (loss) from interest rate swap options, net',     category: 'B' },
  { code: '312N',     cname: '業外─金融資產透過公允價值衡量之淨利益(損失)',     ename: 'Valuation gains (losses) on non-operating financial products at fv thro. p/l',     category: 'B' },
  { code: '312O',     cname: '業外─金融負債透過公允價值衡量之淨利益(損失)',     ename: 'Valuation gains (losses) on non-operating financial liabilities at fv thro. p/l',     category: 'B' },
  { code: '312P',     cname: '業外─其他利益及損失',     ename: 'Other gains and losses, net',     category: 'B' },
  { code: '312S',     cname: '業外─選擇權契約淨利益(損失)',     ename: 'Non-Operating - Options Gain/Loss',     category: 'B' },
  { code: '312T',     cname: '業外─期貨契約淨利益(損失)',     ename: 'Non-Operating - Futures Gain/Loss',     category: 'B' },
  { code: '312U',     cname: '業外─利息收支',     ename: 'Financial income/cost',     category: 'B' },
  { code: '312V',     cname: '衍生性金融商品淨損益─櫃檯─其他衍生性金融商品淨利益(損失)',     ename: 'Derivative Gain/Loss - Others',     category: 'B' },
  { code: '312W',     cname: '衍生性金融商品淨損益─櫃檯─資產交換選擇權淨利益(損失)',     ename: 'Gain (loss) from asset swap options, net',     category: 'B' },
  { code: '312X',     cname: '衍生性金融商品淨損益─櫃檯─利率選擇權淨利益(損失)',     ename: 'Valuation gain (loss) from interest rate options, net',     category: 'B' },
  { code: '312Y',     cname: '衍生性金融商品淨損益─期貨─選擇權交易淨利益(損失)',     ename: 'Option trading gain (loss), net',     category: 'B' },
  { code: '312Z',     cname: '衍生性金融商品淨損益─期貨─期貨契約淨利益(損失)',     ename: 'Futures contract gain (loss), net',     category: 'B' },
  { code: '3130',     cname: '退回及折讓',     ename: 'Sales Discounts and Allowances',     category: 'B' },
  { code: '3140',     cname: '出售證券淨利損─避險',     ename: 'Gains (losses) on sale of securities-hedging, net',     category: 'B' },
  { code: '3143',     cname: '借券及附賣回債券融券回補淨利益(損失)',     ename: 'G/l  on covering of borrowed securities and bonds with resale agreement',     category: 'B' },
  { code: '3144',     cname: '發行認購(售)權證發行淨利益(損失)',     ename: 'Gains (losses) from issuance of call (put) warrants, net',     category: 'B' },
  { code: '3149',     cname: '發行權證利益─到期前履約利益',     ename: 'Gains on exercise of call (put) warrants before maturity',     category: 'B' },
  { code: '314A',     cname: '發行權證利益─逾期失效利益',     ename: 'Gains on expired call (put) warrants',     category: 'B' },
  { code: '314B',     cname: '發行權證費用',     ename: 'Expenses arising from issuance of call (put) warrants',     category: 'B' },
  { code: '3150',     cname: '受託結算交割服務費收入',     ename: 'Total revenue from consignment of clearing and settlement',     category: 'B' },
  { code: '3152',     cname: '衍生工具淨利損─櫃檯',     ename: 'Gain (loss) from derivatives-OTC, net',     category: 'B' },
  { code: '3161',     cname: '顧問費收入',     ename: 'Total revenue from advisory',     category: 'B' },
  { code: '3165',     cname: '衍生工具淨利損─期貨',     ename: 'Gain (loss) from derivatives-futures, net',     category: 'B' },
  { code: '3166',     cname: '發行權證淨損益─負債價值變動淨利益(損失)',     ename: 'Gains (losses) on changes in fair value of call (put) warrant liabilities, net',     category: 'B' },
  { code: '3167',     cname: '發行權證淨損益─再買回價值變動淨利益(損失)',     ename: 'Gains (losses) on changes in fair value for redeem of call (put) warrants, net',     category: 'B' },
  { code: '3171',     cname: '透過損益按公允價值衡量之金融資產及負債損益',     ename: 'Gain (loss) on fin. asset or liab. measured at fair value through profit or loss',     category: 'B' },
  { code: '3172',     cname: '備供出售金融資產已實現損益',     ename: 'Realized gain (loss) on available-for-sale financial assets',     category: 'B' },
  { code: '3173',     cname: '持至到期日金融資產已實現損益',     ename: 'Realized gain (loss) on held-to-maturity financial assets',     category: 'B' },
  { code: '3174',     cname: '營業證券透過公允價值衡量之淨利益(損失)合計',     ename: 'Valuation gains (losses) on operating securities at fair value through p/l',     category: 'B' },
  { code: '3175',     cname: '營業證券透過公允價值衡量之淨利益(損失)─自營',     ename: 'Valuation gain(losses) on operating securities at fair val  ue through p/l',     category: 'B' },
  { code: '3176',     cname: '營業證券透過公允價值衡量之淨利益(損失)─承銷',     ename: 'Valuation gain(losses) on operating securities at fair val  ue through PL',     category: 'B' },
  { code: '3177',     cname: '營業證券透過公允價值衡量之淨利益(損失)─避險',     ename: 'Valuation gains (losse) on operating securities at fair val ue through p/l',     category: 'B' },
  { code: '3178',     cname: '應回補債券透過公允價值衡量之淨利益(損失)─避險',     ename: 'Valuation g/l on settlement coverage bonds payable of short sale at fv thr. p/l',     category: 'B' },
  { code: '3179',     cname: '借券及附賣回債券融券透過損益按公允價值衡量之淨利益(損失)',     ename: 'Valuation gains (losses) on borrowed securities and bonds with resale agreements',     category: 'B' },
  { code: '3180',     cname: '違約證券透過損益按公允價值衡量之淨利益(損失)',     ename: 'Valuation gains (losses) on securities held for customer default at fv thro. p/l',     category: 'B' },
  { code: '3181',     cname: '期貨交易保證金─有價證券透過損益按公允價值衡量之淨利(損)',     ename: 'Valuation gains (losses) on securities for futures margin at fv thro. p/l',     category: 'B' },
  { code: '3182',     cname: '營業票券透過損益按公允價值衡量之淨利益(損失)',     ename: 'Valuation gains (losses) on bills held for operations at fv thro. p/l',     category: 'B' },
  { code: '3183',     cname: '營業證券出售淨利益(損失)',     ename: 'Gains (losses) on sale of operating securities, net',     category: 'B' },
  { code: '3200',     cname: '營業成本',     ename: 'Total operating costs',     category: 'B' },
  { code: '3203',     cname: '成本─租金成本',     ename: 'Operating Cost - Rent',     category: 'B' },
  { code: '3204',     cname: '成本─處分投資成本',     ename: 'Operating Cost - Disposal of Investments',     category: 'B' },
  { code: '3205',     cname: '成本─投資損失',     ename: 'Total investment losses',     category: 'B' },
  { code: '3206',     cname: '銷貨成本',     ename: 'Cost of Goods Sold (A)',     category: 'B' },
  { code: '3208',     cname: '其他營業支出',     ename: 'Other operating expenditure',     category: 'B' },
  { code: '320A',     cname: '成本─出售土地',     ename: 'Operating Cost - Disposal of Lands',     category: 'B' },
  { code: '3212',     cname: '經紀經手費支出',     ename: 'Total brokerage handling fee expense',     category: 'B' },
  { code: '3213',     cname: '自營經手費支出',     ename: 'Total proprietary handling fee expense',     category: 'B' },
  { code: '3214',     cname: '手續費支出',     ename: 'Transaction Fees',     category: 'B' },
  { code: '3218',     cname: '成本─利息支出',     ename: 'Interest expense',     category: 'B' },
  { code: '321E',     cname: '承銷作業手續費支出',     ename: 'Underwriting operation processing fee expenses',     category: 'B' },
  { code: '321G',     cname: '借券交易損失',     ename: 'Loss from securities borrowing transactions',     category: 'B' },
  { code: '321H',     cname: '轉融通手續費支出',     ename: 'Refinancing processing fee expenses',     category: 'B' },
  { code: '3285',     cname: '期貨佣金支出',     ename: 'Total futures commission expense',     category: 'B' },
  { code: '3287',     cname: '結算交割服務費支出',     ename: 'Total expense of clearing and settlement',     category: 'B' },
  { code: '3295',     cname: '營業毛利',     ename: 'Gross profit (loss) from operations',     category: 'B' },
  { code: '3296',     cname: '聯屬公司已〈未〉實現銷貨利益',     ename: 'Realized (Unrealized) Profit - Affliated companies',     category: 'B' },
  { code: '3297',     cname: '已實現銷貨毛利',     ename: 'Realized Gross Operating Profit',     category: 'B' },
  { code: '3300',     cname: '營業費用',     ename: 'Total operating expenses',     category: 'B' },
  { code: '3350',     cname: '營業成本',     ename: 'Total operating costs',     category: 'B' },
  { code: '3352',     cname: '推銷費用',     ename: 'Total selling expenses',     category: 'B' },
  { code: '3355',     cname: '管理費用',     ename: 'Total administrative expenses',     category: 'B' },
  { code: '3356',     cname: '研究發展費',     ename: 'Total research and development expenses',     category: 'B' },
  { code: '3357',     cname: '其他營業費用 (營業費用)',     ename: 'Other Operating Expense',     category: 'B' },
  { code: '3358',     cname: '員工訓練費用 (營業費用)',     ename: 'Staff training expenses',     category: 'B' },
  { code: '3359',     cname: '證券佣金支出',     ename: 'Total securities commission expense',     category: 'B' },
  { code: '335A',     cname: '員工福利費用',     ename: 'Total employee benefits expense',     category: 'B' },
  { code: '335B',     cname: '折舊及攤銷費用',     ename: 'Total depreciation and amortization expense',     category: 'B' },
  { code: '335C',     cname: '營業費用- 業務及管理費',     ename: 'Total other general and administrative expense',     category: 'B' },
  { code: '335H',     cname: '期貨管理費支出',     ename: 'Total futures administrative expenses',     category: 'B' },
  { code: '335I',     cname: '其他營業成本',     ename: 'Total Other operating costs',     category: 'B' },
  { code: '336L',     cname: '其他營業費用',     ename: 'Total other operating expense',     category: 'B' },
  { code: '3395',     cname: '營業利益',     ename: 'Net operating income (loss)',     category: 'B' },
  { code: '339R',     cname: '其他收益及費損淨額',     ename: 'Net other income (expenses)',     category: 'B' },
  { code: '339S',     cname: '其他費用',     ename: 'Other expense, by function',     category: 'B' },
  { code: '3400',     cname: '營業外收入及支出',     ename: 'Total non-operating income and expenses',     category: 'B' },
  { code: '3403',     cname: '保費收入',     ename: 'Total premium',     category: 'B' },
  { code: '3404',     cname: '再保佣金收入',     ename: 'Reinsurance commission received',     category: 'B' },
  { code: '340A',     cname: '淨收益', ename: 'Net income', category: 'B' },
  { code: '340C',     cname: '簽單保費收入',     ename: 'Written premium',     category: 'B' },
  { code: '340D',     cname: '再保費收入',     ename: 'Reinsurance premium',     category: 'B' },
  { code: '340E',     cname: '自留滿期保費收入',     ename: 'Retained earned premium',     category: 'B' },
  { code: '340F',     cname: '業外─營業外損益合計',     ename: 'Total non-operating income and expenses',     category: 'B' },
  { code: '3410',     cname: '利息收入',     ename: 'Total interest income',     category: 'B' },
  { code: '341C',     cname: '利息淨收益',     ename: 'Net income (loss) of interest',     category: 'B' },
  { code: '341Z',     cname: '利息以外淨損益',     ename: 'Net non-interest income (loss)',     category: 'B' },
  { code: '3425',     cname: '攤回再保賠款與給付',     ename: 'Claims recovered from reinsurers',     category: 'B' },
  { code: '3434',     cname: '處分投資利益',     ename: 'Gains on disposals of investments',     category: 'B' },
  { code: '3436',     cname: '金融資產減損迴轉利益',     ename: 'Reversal of impairment loss recognised in profit or loss, financial assets',     category: 'B' },
  { code: '343C',     cname: '採權益法之關聯企業及合資損益',     ename: 'Share of profit(loss) of associates &joint ventures accounted for using eq. meth',     category: 'B' },
  { code: '343H',     cname: '保險負債準備淨變動(淨收益)',     ename: 'Insurance Reserve',     category: 'B' },
  { code: '343I',     cname: '保險業務收益',     ename: 'Net income (loss) of insurance operations',     category: 'B' },
  { code: '343J',     cname: '處分投資損益',     ename: 'Gains or Losses on Disposal of Investment',     category: 'B' },
  { code: '343K',     cname: '股利收入',     ename: 'Revenue from dividends',     category: 'B' },
  { code: '343L',     cname: '採用權益法認列之關聯企業及合資利益之份額',     ename: 'Share of profit of associates and joint ventures accounted for using equity meth',     category: 'B' },
  { code: '3440',     cname: '處分不動產、廠房及設備利益',     ename: 'Gains on disposals of property, plant and equipment',     category: 'B' },
  { code: '3447',     cname: '資產減損迴轉利益',     ename: 'Reversal of Loss on Assets Impairment',     category: 'B' },
  { code: '344A',     cname: '資產減損/ 迴轉',     ename: '(Impairment loss on assets) reversal of impairment loss on assets',     category: 'B' },
  { code: '344B',     cname: '財產交易淨損益',     ename: 'Net gain (loss) on disposal of property',     category: 'B' },
  { code: '344C',     cname: '出售承受擔保品淨損益',     ename: 'Net gain (loss) on sale of foreclosed collaterals',     category: 'B' },
  { code: '3450',     cname: '手續費收入',     ename: 'Total fee income',     category: 'B' },
  { code: '345A',     cname: '手續費淨收益',     ename: 'Net service fee (charge) income (losses)',     category: 'B' },
  { code: '345C',     cname: '不動產、廠房及設備減損迴轉利益',     ename: 'Reversal of Loss on PP&E',     category: 'B' },
  { code: '345D',     cname: '無形資產減損迴轉利益',     ename: 'Reversal of Loss on Intangible Assets',     category: 'B' },
  { code: '345E',     cname: '其他減損迴轉利益',     ename: 'Other Reversal of Loss',     category: 'B' },
  { code: '3460',     cname: '外幣兌換利益',     ename: 'Foreign exchange gains',     category: 'B' },
  { code: '346A',     cname: '兌換損益',     ename: 'Foreign exchange gain (loss)',     category: 'B' },
  { code: '346B',     cname: '兌換利益(損失)',     ename: 'Foreign exchange gains (losses), investments',     category: 'B' },
  { code: '3480',     cname: '收回呆帳及過期帳轉',     ename: 'Reversal of Bad Debts & Overdue Accounts',     category: 'B' },
  { code: '3484',     cname: '租金收入',     ename: 'Rent income',     category: 'B' },
  { code: '3489',     cname: '其他收入',     ename: 'Other Non-Operating Income',     category: 'B' },
  { code: '348A',     cname: '營業資產出租淨損益',     ename: 'Net income (loss) of renting out operating assets',     category: 'B' },
  { code: '348C',     cname: '其他收入─其他',     ename: 'Other income, others',     category: 'B' },
  { code: '348D',     cname: '被避險項目之淨損益- 公允價值避險',     ename: 'Net income (loss) on hedged item attributable to hedged risk, fair value hedges',     category: 'B' },
  { code: '348E',     cname: '外匯價格變動準備淨變動IS',     ename: 'Net change in reserve for foreign exchange valuation',     category: 'B' },
  { code: '348G',     cname: '成本衡量之金負淨損益',     ename: 'Net gain (loss) on financial liabilities at cost',     category: 'B' },
  { code: '348H',     cname: '證券承銷收入淨額',     ename: 'Net securities underwriting income',     category: 'B' },
  { code: '348I',     cname: '證券自營費用',     ename: 'Total securities proprietary expense',     category: 'B' },
  { code: '348J',     cname: '其他淨投資損益',     ename: 'Other net income(loss) from investments',     category: 'B' },
  { code: '348K',     cname: '其他營業收入－利息收入',     ename: 'Interest income',     category: 'B' },
  { code: '348L',     cname: '其他營業收入－其他',     ename: 'Other Operating Costs',     category: 'B' },
  { code: '3491',     cname: '違約金收入',     ename: 'Income from counter-party default',     category: 'B' },
  { code: '3492',     cname: '投資性不動產損益',     ename: 'Gain (loss) on investment property',     category: 'B' },
  { code: '3493',     cname: '沖銷逾期應付帳款利益',     ename: 'Gains on write-off of past due payable',     category: 'B' },
  { code: '3494',     cname: '壞帳轉回利益',     ename: 'Gains on doubtful debt recoveries',     category: 'B' },
  { code: '3495',     cname: '其他營業收入',     ename: 'Total other operating income',     category: 'B' },
  { code: '3497',     cname: '分離帳戶保險商品利益',     ename: 'Income on insurance product, separated account',     category: 'B' },
  { code: '3498',     cname: '賠償收入',     ename: 'Compensation Income',     category: 'B' },
  { code: '349A',     cname: '其他利息以外淨損益',     ename: 'Net other non-interest income (loss)',     category: 'B' },
  { code: '349B',     cname: '成本衡量之金資淨損益',     ename: 'Net gain (loss) on financial assets at cost',     category: 'B' },
  { code: '349C',     cname: '無活絡市場淨投資損益',     ename: 'Net investment gain (loss) on debts investment without active market',     category: 'B' },
  { code: '349D',     cname: '證券經紀收入淨額',     ename: 'Net securities brokering income',     category: 'B' },
  { code: '349E',     cname: '避險工具之淨損益- 公允價值避險',     ename: 'Net income (loss) on hedging instrument, fair value hedges',     category: 'B' },
  { code: '349Z',     cname: '其他什項損益',     ename: 'Other Non-Interest Gain/Loss',     category: 'B' },
  { code: '34AW',     cname: '權利金收入',     ename: 'Revenue from royalties',     category: 'B' },
  { code: '34AX',     cname: '廉價購買收益',     ename: 'Gain recognised in bargain purchase transaction',     category: 'B' },
  { code: '34AY',     cname: '資產評價利益',     ename: 'Gain on Valuation of Assets',     category: 'B' },
  { code: '34BD',     cname: '透過損益按公允價值衡量之金融資產（負債）利益',     ename: 'Gains on financial assets (liabilities) at fair value through profit or loss',     category: 'B' },
  { code: '34BE',     cname: '買回公司債利益',     ename: 'Gains on corporate bonds repurchases',     category: 'B' },
  { code: '34BF',     cname: '補助收益',     ename: 'Government grants income',     category: 'B' },
  { code: '3501',     cname: '財務成本',     ename: 'Finance costs, net',     category: 'B' },
  { code: '3503',     cname: '保險給付與賠款',     ename: 'Total insurance claim payment',     category: 'B' },
  { code: '3505',     cname: '未滿期保費準備淨變動',     ename: 'Net change in unearned premiums reserve',     category: 'B' },
  { code: '3506',     cname: '責任準備淨變動',     ename: 'Net change in liability reserve',     category: 'B' },
  { code: '3507',     cname: '特別準備淨變動',     ename: 'Net change in special claim reserve',     category: 'B' },
  { code: '350J',     cname: '承保費用',     ename: 'Acquisition expense',     category: 'B' },
  { code: '350K',     cname: '佣金費用',     ename: 'Total commission expense',     category: 'B' },
  { code: '3510',     cname: '利息支出',     ename: 'Total Interest expense',     category: 'B' },
  { code: '3514',     cname: '再保費支出',     ename: 'Reinsurance expense',     category: 'B' },
  { code: '351C',     cname: '負債性特別股股息',     ename: 'Dividends on preference share liabilities',     category: 'B' },
  { code: '351N',     cname: '財務成本-其他',     ename: 'Finance costs, other',     category: 'B' },
  { code: '351R',     cname: '優存超額利息',     ename: 'Preferential deposit interest',     category: 'B' },
  { code: '3520',     cname: '自留保險賠款與給付',     ename: 'Retained claim payment',     category: 'B' },
  { code: '3525',     cname: '負債適足準備淨變動',     ename: 'Net change in liability adequacy reserve',     category: 'B' },
  { code: '3526',     cname: '保費不足準備淨變動',     ename: 'Net change in premium deficiency reserve',     category: 'B' },
  { code: '3527',     cname: '其他準備淨變動',     ename: 'Net change in other reverses',     category: 'B' },
  { code: '3528',     cname: '保險契約準備淨變動- 金融商品',     ename: 'Net change in reserve for insurance with nature of financial instrument',     category: 'B' },
  { code: '3530',     cname: '採用權益法認列之關聯企業及合資損失之份額',     ename: 'Share of loss of associates and joint ventures accounted for using equity method',     category: 'B' },
  { code: '3532',     cname: '賠款準備淨變動',     ename: 'Net change in claim reserve',     category: 'B' },
  { code: '3534',     cname: '處分投資損失',     ename: 'Losses on disposals of investments',     category: 'B' },
  { code: '3536',     cname: '金融資產減損損失',     ename: 'Impairment loss on financial assets',     category: 'B' },
  { code: '3540',     cname: '處分不動產、廠房及設備損失',     ename: 'Losses on disposals of property, plant and equipment',     category: 'B' },
  { code: '3545',     cname: '放款呆帳費用',     ename: 'Provision Bad Debts',     category: 'B' },
  { code: '3547',     cname: '資產減損損失',     ename: 'Impairment loss recognised in profit or loss, property, plant and equipment',     category: 'B' },
  { code: '354B',     cname: '信用卡呆帳費用',     ename: 'Provision Bad Debts on Credit Card',     category: 'B' },
  { code: '354C',     cname: '其他各項提存/ 迴轉',     ename: 'Provision of Other Items',     category: 'B' },
  { code: '354D',     cname: '出售不良債權淨損益',     ename: 'Net gain (loss) on sale of non-performing loans',     category: 'B' },
  { code: '354E',     cname: '保險負債淨變動',     ename: 'Net change in insurance liability',     category: 'B' },
  { code: '354W',     cname: '不動產、廠房及設備減損損失',     ename: 'PP&E Impairment Loss',     category: 'B' },
  { code: '354X',     cname: '無形資產減損損失',     ename: 'Intangible Assets Impairment Loss',     category: 'B' },
  { code: '354Z',     cname: '其他減損損失',     ename: 'Other Impairment Loss',     category: 'B' },
  { code: '3551',     cname: '呆帳費用及保證責任準備提存',     ename: 'Total bad debts expense and guarantee liability provision',     category: 'B' },
  { code: '3552',     cname: '保證責任準備提存',     ename: 'Provision and bad debts expense of guarantee liability',     category: 'B' },
  { code: '3553',     cname: '其他各項提存',     ename: 'Other Provisions',     category: 'B' },
  { code: '3560',     cname: '外幣兌換損失',     ename: 'Foreign exchange losses',     category: 'B' },
  { code: '358E',     cname: '合約損失',     ename: 'Guarantee contracts losses',     category: 'B' },
  { code: '3597',     cname: '分離帳戶保險商品費用',     ename: 'Disbursements on insurance product, separated account',     category: 'B' },
  { code: '3599',     cname: '停工損失',     ename: 'Losses on work stoppages',     category: 'B' },
  { code: '359A',     cname: '賠償損失',     ename: 'Compensation losses',     category: 'B' },
  { code: '359T',     cname: '資產評價損失',     ename: 'Loss on Contract',     category: 'B' },
  { code: '359U',     cname: '透過損益按公允價值衡量之金融資產（負債）損失',     ename: 'Losses on financial assets (liabilities) at fair value through profit or loss',     category: 'B' },
  { code: '359V',     cname: '其他利益及損失─其他',     ename: 'Other gains and losses, other',     category: 'B' },
  { code: '359W',     cname: '其他利益及損失',     ename: 'Other gains and losses, net',     category: 'B' },
  { code: '35BD',     cname: '買回公司債損失',     ename: 'Losses on corporate bonds repurchases',     category: 'B' },
  { code: '3600',     cname: '費用合計',     ename: 'Total expenditure and expense',     category: 'B' },
  { code: '3700',     cname: '營業外收入及支出',     ename: 'Total non-operating income and expenses',     category: 'B' },
  { code: '3701',     cname: '營業外收入及支出─其他',     ename: 'Non-operating income and expenses, other',     category: 'B' },
  { code: '3900',     cname: '稅前淨利',     ename: 'Profit (loss) before tax',     category: 'B' },
  { code: '3910',     cname: '所得稅費用',     ename: 'Total tax expense (income)',     category: 'B' },
  { code: '3920',     cname: '繼續營業單位損益',     ename: 'Profit (loss) from continuing operations',     category: 'B' },
  { code: '3925',     cname: '停業單位損益',     ename: 'Total profit (loss) from discontinued operations',     category: 'B' },
  { code: '3947',     cname: '其他綜合損益─OCI',     ename: 'Other comprehensive income, net',     category: 'B' },
  { code: '3948',     cname: '重估價之利益（損失）─OCI',     ename: 'Other comprehensive income, before tax, gains (losses) on revaluation',     category: 'B' },
  { code: '3949',     cname: '確定福利計畫精算損益─OCI',     ename: 'Other comprehensive income, before tax, actuarial gains (losses) on defined bene',     category: 'B' },
  { code: '394A',     cname: '國外營運機構財務報表換算之兌換差額─OCI',     ename: 'Other comprehensive income, before tax, exchange differences on translation',     category: 'B' },
  { code: '394B',     cname: '備供出售金融資產未實現評價損益─OCI',     ename: 'Other comprehensive income, before tax, available-for-sale financial assets',     category: 'B' },
  { code: '394C',     cname: '現金流量避險─OCI',     ename: 'Other comprehensive income, before tax, cash flow hedges',     category: 'B' },
  { code: '394D',     cname: '其他綜合損益─其他─OCI',     ename: 'Other Comprehensive Income - Other-OCI',     category: 'B' },
  { code: '394E',     cname: '權益工具投資損益─OCI',     ename: 'Other comprehensive income, before tax, gains (losses) from investments in equit',     category: 'B' },
  { code: '394F',     cname: '國外營運機構淨投資避險─OCI',     ename: 'Other comprehensive income, before tax, hedges of net investments in foreign ope',     category: 'B' },
  { code: '394G',     cname: '採用權益法認列之關聯企業及合資之其他綜合損益之份額─OCI',     ename: 'Total share of other comprehensive income of associates and joint ventures accou',     category: 'B' },
  { code: '394H',     cname: '與其他綜合損益組成部分相關之所得稅─OCI',     ename: 'Income tax relating to components of other comprehensive income',     category: 'B' },
  { code: '3950',     cname: '歸屬母公司淨利(損)',     ename: 'Profit (loss), attributable to owners of parent',     category: 'B' },
  { code: '3956',     cname: '綜合損益歸屬母公司',     ename: 'Comprehensive income, attributable to owners of parent',     category: 'B' },
  { code: '395S',     cname: '稀釋稅後淨利',     ename: 'Diluted Net Income',     category: 'B' },
  { code: '3960',     cname: '歸屬非控制權益淨利(損)',     ename: 'Profit (loss), attributable to non-controlling interests',     category: 'B' },
  { code: '3961',     cname: '綜合損益歸屬非控制權益',     ename: 'Comprehensive income, attributable to non-controlling interests',     category: 'B' },
  { code: '3964',     cname: '歸屬共同控制下前手權益淨利(損)',     ename: 'Profit (loss), attributable to interests in the former jointly controlled entity',     category: 'B' },
  { code: '3966',     cname: '合併前非屬共同控制股權損益',     ename: 'Comprehensive income, attributable to non-controlling interests in pre-aquisitio',     category: 'B' },
  { code: '3967',     cname: '綜合損益歸屬共同控制下前手權益',     ename: 'Comprehensive income, attributable to non-controlling interest in pre-aquisition',     category: 'B' },
  { code: '3970',     cname: '合併總損益',     ename: 'Profit (loss)',     category: 'B' },
  { code: '3971',     cname: '本期綜合損益總額',     ename: 'Comprehensive income',     category: 'B' },
  { code: '3990',     cname: '每股盈餘（元）',     ename: 'Total basic earnings per share',     category: 'B' },
  { code: '3995',     cname: '每股盈餘─完全稀釋',     ename: 'Total diluted earnings per share',     category: 'B' },
  { code: '4150',     cname: '普通股─現金股利',     ename: 'Cash Dividends - Common Stock',     category: 'C' },
  { code: '4151',     cname: '普通股每股現金股利(元)',     ename: 'Cash Dividend Per Share',     category: 'C' },
  { code: '4155',     cname: '普通股─股票股利',     ename: 'Stock Dividends - Common Stock',     category: 'C' },
  { code: '4161',     cname: '每股股票股利─盈餘(元)',     ename: 'Stock Dividend Per Share - Retained earnings',     category: 'C' },
  { code: '4166',     cname: '每股現金股利─盈餘(元)',     ename: 'Cash Dividend Per Share - Retained earnings',     category: 'C' },
  { code: '4300',     cname: '資本公積轉增資',     ename: 'Stock dividends from capital surplus',     category: 'C' },
  { code: '4301',     cname: '每股股票股利─公積(元)',     ename: 'Stock Dividend Per Share - capital surplus',     category: 'C' },
  { code: '4302',     cname: '資本公積現金',     ename: 'Cash dividends from capital surplus',     category: 'C' },
  { code: '4303',     cname: '每股現金股利─公積(元)',     ename: 'Cash Dividend Per Share  - capital surplus',     category: 'C' },
  { code: '7002',     cname: '稅前淨利-CFO',     ename: 'Pre-Tax Income(CF)',     category: 'D' },
  { code: '720C',     cname: '利息收現─CFO',     ename: 'Interest received',     category: 'D' },
  { code: '7210',     cname: '來自營運之現金流量',     ename: 'Net cash flows from (used in) operating activities',     category: 'D' },
  { code: '7211',     cname: '折舊',     ename: 'Depreciation expense',     category: 'D' },
  { code: '7212',     cname: '攤提',     ename: 'Amortization expense',     category: 'D' },
  { code: '7213',     cname: '採用權益法認列之關聯企業及合資利益份額CFO',     ename: 'Share of loss (profit) of associates and joint ventures accounted for using equi',     category: 'D' },
  { code: '7214',     cname: '採用權益法認列之關聯企業及合資損失份額CFO',     ename: 'Investment Loss - Equity Method-CFO',     category: 'D' },
  { code: '721A',     cname: '透過損益按公允價值衡量之金融資產及負債淨損失(利益)',     ename: 'Net loss (gain) on financial assets or liabilities at fair value through p/l',     category: 'D' },
  { code: '721B',     cname: '備供出售金資淨損(益)',     ename: 'Net loss (gain) on available for sale financial assets-CFO',     category: 'D' },
  { code: '721C',     cname: '持至到期金資淨損(益)',     ename: 'Net loss (gain) on held-to-maturity financial assets-CFO',     category: 'D' },
  { code: '721D',     cname: '以成本衡量金資淨損(益)',     ename: 'Net loss (gain) on financial assets or liabilities at cost-CFO',     category: 'D' },
  { code: '721E',     cname: '避險金資淨損(益)',     ename: 'Loss(Gain) on Disposal of Financial Asset at Hedge-CFO',     category: 'D' },
  { code: '721F',     cname: '無活絡市場金資淨損(益)',     ename: 'Net loss (gain) on bond investment without active market-CFO',     category: 'D' },
  { code: '721G',     cname: '其他金資淨損(益)',     ename: 'Loss(Gain) on Disposal of Other Financial Assets-CFO',     category: 'D' },
  { code: '721I',     cname: '無活絡市場之債券投資(增)減CFO',     ename: 'Decrease (increase) in bond investment without active market',     category: 'D' },
  { code: '721J',     cname: '利息收入CFO',     ename: 'Interest income',     category: 'D' },
  { code: '721K',     cname: '利息支出CFO',     ename: 'Interest expense -CFO',     category: 'D' },
  { code: '721M',     cname: '利息淨收益-CFO',     ename: 'Net Interest Income-CFO',     category: 'D' },
  { code: '721N',     cname: '金融資產重分類淨損失(利益)',     ename: 'Net (loss) gain on reclassification of financial assets',     category: 'D' },
  { code: '721P',     cname: '透過損益按公允價值衡量金融資產及負債之淨損失（利益）',     ename: 'Net loss (gain) on financial assets or liabilities at FV through profit or loss',     category: 'D' },
  { code: '7221',     cname: '處分不動產、廠房及設備收益CFO',     ename: 'Gain on Disposal of Fixed Assets-CFO',     category: 'D' },
  { code: '7222',     cname: '處分不動產、廠房及設備損失CFO',     ename: 'Loss on Disposal of Fixed Assets-CFO',     category: 'D' },
  { code: '7224',     cname: '資產減損迴轉利益CFO',     ename: 'Reversal of impairment loss on non-financial assets',     category: 'D' },
  { code: '7225',     cname: '資產減損損失CFO',     ename: 'Impairment loss on non-financial assets',     category: 'D' },
  { code: '7227',     cname: '股份基礎給付酬勞成本',     ename: 'Share-based payments',     category: 'D' },
  { code: '722A',     cname: '處分擔保品收益-CFO',     ename: 'Gain on Disposal of Collerals-CFO',     category: 'D' },
  { code: '722B',     cname: '處分擔保品損失-CFO',     ename: 'Loss on Disposal of Collerals-CFO',     category: 'D' },
  { code: '722F',     cname: '處分投資性不動產損(益)',     ename: 'Loss (gain) on disposal of investment properties',     category: 'D' },
  { code: '722G',     cname: '處分無形資產損(益)',     ename: 'Loss (gain) on disposal of intangible assets',     category: 'D' },
  { code: '722H',     cname: '買回公司債損(益)CFO',     ename: 'Loss (gain) on corporate bonds repurchases -CFO',     category: 'D' },
  { code: '7233',     cname: '處分投資損失CFO',     ename: 'Loss (gain) on disposal of investments accounted for using equity method',     category: 'D' },
  { code: '7234',     cname: '處分投資利益CFO',     ename: 'Loss (gain) on disposal of investments',     category: 'D' },
  { code: '723A',     cname: '透過損益按公允價值衡量金融資產及負債之淨損失（利益）-CFO',     ename: 'Net loss (gain) on fin. assets or liab. at fair value through profit or loss-CFO',     category: 'D' },
  { code: '723C',     cname: '透過損益按公允價值衡量金融資產〈增〉減CFO',     ename: 'Decrease (increase) in financial assets held for trading',     category: 'D' },
  { code: '723D',     cname: '備供出售金融資產〈增〉減CFO',     ename: 'Decrease(Increase) in Financial Assets at AFS-CFO',     category: 'D' },
  { code: '723E',     cname: '避險之衍生性金融資產〈增〉減CFO',     ename: 'Decrease (increase) in derivative financial assets for hedging',     category: 'D' },
  { code: '723F',     cname: '其他金融資產〈增〉減─CFO',     ename: 'Decrease (increase) in other financial assets',     category: 'D' },
  { code: '723G',     cname: '金融資產匯率影響數',     ename: 'Net loss (gain) on non-operating financial instruments at fair value',     category: 'D' },
  { code: '723H',     cname: '金融商品減損損失CFO',     ename: 'Impairment loss on financial assets -CFO',     category: 'D' },
  { code: '723I',     cname: '透過損益按公允價值衡量金融負債〈減〉',     ename: 'Increase (decrease) in financial liabilities held for trading',     category: 'D' },
  { code: '723J',     cname: '避險之衍生性金融負債增〈減〉─CFO',     ename: 'Increase (decrease) in derivative financial liabilities for hedging',     category: 'D' },
  { code: '723K',     cname: '以成本衡量之金融負債增〈減〉',     ename: 'Increase (decrease) in financial liabilities at cost',     category: 'D' },
  { code: '723L',     cname: '其他金融負債增〈減〉CFO',     ename: 'Increase (decrease) in other financial liabilities',     category: 'D' },
  { code: '723M',     cname: '金融商品減損迴轉利益CFO',     ename: 'Reversal of impairment loss on financial assets',     category: 'D' },
  { code: '723N',     cname: '以成本衡量之金融資產〈增〉減CFO',     ename: 'Decrease(Increase) in Financial Assets Carried at Cost (CFO)',     category: 'D' },
  { code: '723R',     cname: '期貨交易人權益增(減)',     ename: 'Increase (decrease) in futures traders\' equity',     category: 'D' },
  { code: '723T',     cname: '附賣回債券投資(增)減',     ename: 'Decrease (increase) in bond investments under resale agreements',     category: 'D' },
  { code: '723W',     cname: '持有至到期日金融資產〈增〉減CFO',     ename: 'Increase (Decrease) in Financial Asset at HTM (CFO)',     category: 'D' },
  { code: '723Z',     cname: '附買回債券負債增(減)-CFO',     ename: 'Increase (decrease) in notes and bonds issued under repurchase agreement-CFO',     category: 'D' },
  { code: '7241',     cname: '具金融商品性質之保險契約準備淨變動-CFO',     ename: 'Net change in reserve for insurance with nature of financial instrument-CFO',     category: 'D' },
  { code: '7243',     cname: '提列各項準備',     ename: 'Provision of Reserve',     category: 'D' },
  { code: '7244',     cname: '回轉各項準備',     ename: 'Reversal of Reserve',     category: 'D' },
  { code: '724D',     cname: '各項保險負債淨變動-CFO',     ename: 'Net change in insurance liabilities-CFO',     category: 'D' },
  { code: '724G',     cname: '外匯價格變動準備淨變動-O',     ename: 'Net change in reserve for foreign exchange valuation-CFO',     category: 'D' },
  { code: '724H',     cname: '借券擔保價款(增)減',     ename: 'Decrease (increase) in security borrowing collateral price',     category: 'D' },
  { code: '724I',     cname: '借券存出保證金(增)減',     ename: 'Decrease (increase) in security borrowing margin',     category: 'D' },
  { code: '724J',     cname: '融券存入保證金增(減)',     ename: 'Increase (decrease) in securities financing refundable deposits',     category: 'D' },
  { code: '724K',     cname: '其他各項負債準備淨變動-CFO',     ename: 'Net change in other provisions-CFO',     category: 'D' },
  { code: '724L',     cname: '收取股利─CFO',     ename: 'Dividends received',     category: 'D' },
  { code: '724M',     cname: '存放央行及拆借同業(增)減',     ename: 'Decrease (increase) in due from the central bank and call loans to banks',     category: 'D' },
  { code: '724P',     cname: '借券存入保證金增(減)',     ename: 'Increase (decrease) in refundable deposit',     category: 'D' },
  { code: '7253',     cname: '提列員工退休金準備',     ename: 'Employee Pension Provision',     category: 'D' },
  { code: '7260',     cname: '呆帳費用提列(轉列收入)數-CFO',     ename: 'Provision (reversal of provision) for bad debt expense-CFO',     category: 'D' },
  { code: '7261',     cname: '保證責任準備淨變動-CFO',     ename: 'Net change in provisions for guarantee liabilities-CFO',     category: 'D' },
  { code: '7266',     cname: '出售不良債權損(益)-CFO',     ename: 'Loss (gain) on disposal of non-performing loans-CFO',     category: 'D' },
  { code: '726A',     cname: '呆帳費用與保證責任準備提存-CFO',     ename: 'Provision of Bad Debt and Recognized Resposibility Reserve-CFO',     category: 'D' },
  { code: '726B',     cname: '資產證券化損失(利益)-CFO',     ename: 'Loss (gain) on financial assets securitization-CFO',     category: 'D' },
  { code: '7278',     cname: '預付款〈增〉減',     ename: 'Decrease(Increase) in Prepayments',     category: 'D' },
  { code: '727B',     cname: '客戶保證金專戶(增)減',     ename: 'Decrease (increase) in customer margin account',     category: 'D' },
  { code: '727C',     cname: '應收證券融資款(增)減',     ename: '(Increase) Decrease in margin loans receivable',     category: 'D' },
  { code: '727D',     cname: '金融資產重分類淨損失(利益)',     ename: 'Net (loss) gain on reclassification of financial assets',     category: 'D' },
  { code: '727G',     cname: '營業外金融商品按公允價值衡量之損失(利益)',     ename: 'Loss(Gain) on Non-Operating FVPL Assets',     category: 'D' },
  { code: '727H',     cname: '未實現認購(售)權證發行損失(利益)',     ename: 'Unrealized gain (loss) on issuance of call or put warrants',     category: 'D' },
  { code: '727I',     cname: '附賣回票券投資(增)減',     ename: 'Decrease (increase) in bill investments under resale agreements',     category: 'D' },
  { code: '727J',     cname: '附買回票券負債增(減)',     ename: 'Increase (decrease) in liabilities for bills with attached repurchase agreements',     category: 'D' },
  { code: '727K',     cname: '應計退休金負債增(減)',     ename: 'Increase (decrease) in accrued pension liability',     category: 'D' },
  { code: '727M',     cname: '轉融通保證金(增)減',     ename: '(Increase) Decrease in refinancing guaranty deposits',     category: 'D' },
  { code: '727N',     cname: '應收轉融通擔保價款(增)',     ename: '(Increase) Decrease in guaranteed proceeds receivable from refinancing',     category: 'D' },
  { code: '727Z',     cname: '附買回債券負債增(減)',     ename: 'Increase (decrease) in liabilities for bonds with attached repurchase agreements',     category: 'D' },
  { code: '7280',     cname: '其他應付款增〈減〉',     ename: 'Increase(Decrease) in Other Accounts Payable',     category: 'D' },
  { code: '7282',     cname: '預收款增〈減〉',     ename: 'Increase (decrease) in receipts in advance',     category: 'D' },
  { code: '728C',     cname: '應付融券擔保價款增(減)',     ename: 'Increase (decrease) in deposits payable for securities financing',     category: 'D' },
  { code: '728D',     cname: '遞延手續費收入增(減)',     ename: 'Increase (decrease) in deferred fee income',     category: 'D' },
  { code: '729B',     cname: 'CFO─調整項(出貨)',     ename: 'Other Adjustment-Operating Activities',     category: 'D' },
  { code: '7300',     cname: '投資活動之現金流量',     ename: 'Net cash flows from (used in) investing activities',     category: 'D' },
  { code: '7301',     cname: '存出保證金增加-CFI',     ename: 'Increase in refundable deposits-CFI',     category: 'D' },
  { code: '7302',     cname: '存出保證金減少-CFI',     ename: 'Decrease in refundable deposits-CFI',     category: 'D' },
  { code: '7303',     cname: '存出再保責任準備金增加-CFI',     ename: 'Increase in reinsurance liability reserve contribute',     category: 'D' },
  { code: '7304',     cname: '存出再保責任準備金減少-CFI',     ename: 'Decrease in reinsurance liability reserve contribute',     category: 'D' },
  { code: '7309',     cname: '金融資產證券化款項-CFI',     ename: 'Financial Asset Securitization-CFI',     category: 'D' },
  { code: '730C',     cname: '附賣回票券及債券(增)減-CFI',     ename: 'Resell Bond(Increase)-CFI',     category: 'D' },
  { code: '731A',     cname: '放款減少 (增加)',     ename: 'Decrease(Increase) Loan',     category: 'D' },
  { code: '7323',     cname: '處分不動產廠房設備(含預付)',     ename: 'Sale of Fixed Assets',     category: 'D' },
  { code: '7324',     cname: '購置不動產廠房設備(含預付)',     ename: 'Purchase of Fixed Assets',     category: 'D' },
  { code: '732A',     cname: '購買承受擔保品',     ename: 'Purchase of foreclosed collateral',     category: 'D' },
  { code: '732B',     cname: '出售承受擔保品款',     ename: 'Proceed from disposal of foreclosed collateral',     category: 'D' },
  { code: '732C',     cname: '營業保證金(增)減CFI',     ename: 'Dec(Inc) Guarantee Funds (CFI)',     category: 'D' },
  { code: '732D',     cname: '交割結算金(增)減CFI',     ename: 'Dec(Inc) Settlement Funds (CFI)',     category: 'D' },
  { code: '732E',     cname: '其他應收款(增)減CFI',     ename: 'Dec(Inc) Other Receivables (CFI)',     category: 'D' },
  { code: '7331',     cname: '應收款項增〈減〉CFI',     ename: 'Increase(Decrease) in Receivables CFI',     category: 'D' },
  { code: '7333',     cname: '股利收入CFO',     ename: 'Dividend income',     category: 'D' },
  { code: '7335',     cname: '出售投資',     ename: 'Sale of Long-Term Investments',     category: 'D' },
  { code: '7336',     cname: '新增投資',     ename: 'Purchase of Long-Term Investments',     category: 'D' },
  { code: '7340',     cname: '投資性不動產出售(購)',     ename: 'Sale(Purchase) in Property Investments',     category: 'D' },
  { code: '7347',     cname: '處分投資性不動產',     ename: 'Proceeds from disposal of investment properties',     category: 'D' },
  { code: '7348',     cname: '取得投資性不動產',     ename: 'Acquisition of investment properties',     category: 'D' },
  { code: '7350',     cname: '購併他公司支付現金淨額',     ename: 'Net cash flow from acquisition of subsidiaries',     category: 'D' },
  { code: '7352',     cname: '取得購併公司現金',     ename: 'Cash Acquired in Merger',     category: 'D' },
  { code: '7353',     cname: '處分子公司現金流出CFF',     ename: 'Cash outflow from disposal of subsidiaries',     category: 'D' },
  { code: '7361',     cname: '（買）賣透過損益按公允價值衡量之金融資產CFI',     ename: 'Decrease(Increase) in Financial Assets at FVPL (CFI)',     category: 'D' },
  { code: '7362',     cname: '（買）賣備供出售金融資產CFI',     ename: 'Decrease(Increase) in Financial Assets at AFS (CFI)',     category: 'D' },
  { code: '7363',     cname: '持有至到期日金融資產〈增〉減CFI',     ename: 'Decrease(Increase) in Financial Assets at HTM (CFI)',     category: 'D' },
  { code: '7364',     cname: '以成本衡量之金融資產損〈增〉減CFI',     ename: 'Decrease(Increase) in Financial Assets Carried at Cost (CFI)',     category: 'D' },
  { code: '7365',     cname: '無活絡市場之債券投資 〈增〉減CFI',     ename: 'Decrease(Increase) in Bond Investments with No Active Market',     category: 'D' },
  { code: '7366',     cname: '避險之衍生性金融資產〈增〉減CFI',     ename: 'Decrease(Increase) in Hedging Derivative Financial Assets CFI',     category: 'D' },
  { code: '7367',     cname: '避險之衍生性金融負債增〈減〉CFI',     ename: 'Increase(Decrease) in Hedging Financial Liabilities (CFI)',     category: 'D' },
  { code: '7368',     cname: '其他金融資產〈增〉減CFI',     ename: 'Decrease(Increase) in Other Financial Assets (CFI)',     category: 'D' },
  { code: '736A',     cname: '金融資產證券化款項',     ename: 'Proceeds from financial assets securitization',     category: 'D' },
  { code: '739A',     cname: 'CFI─調整項(出貨)',     ename: 'Other Adjustment from Investment Activities',     category: 'D' },
  { code: '739B',     cname: '收到股利─CFI',     ename: 'Dividends received -CFI',     category: 'D' },
  { code: '739C',     cname: '收到利息─CFI',     ename: 'Interest received -CFI',     category: 'D' },
  { code: '739D',     cname: '退還(支付)所得稅─CFI',     ename: 'Income taxes refund (paid)',     category: 'D' },
  { code: '7400',     cname: '籌資活動之現金流量',     ename: 'Net cash flows from (used in) financing activities',     category: 'D' },
  { code: '7401',     cname: '存入保證金增加-CFF',     ename: 'Increase in guarantee deposits received-CFF',     category: 'D' },
  { code: '7402',     cname: '存入保證金減少-CFF',     ename: 'Decrease in guarantee deposits received-CFF',     category: 'D' },
  { code: '7403',     cname: '存入再保責任準備金增加-CFF',     ename: 'Increase in reinsurance liability reserve received',     category: 'D' },
  { code: '7404',     cname: '存入再保責任準備金減少-CFF',     ename: 'Decrease in reinsurance liability reserve received',     category: 'D' },
  { code: '740B',     cname: '央行及同業融資增(減)',     ename: 'Increase(Decrease) Loan of Central Banl and Other Banks',     category: 'D' },
  { code: '740D',     cname: '附買回票債券增(減)-CFF',     ename: 'Increase(Decrease) Repurchase Bond-CFF',     category: 'D' },
  { code: '7411',     cname: '短期借款增〈減〉',     ename: 'Increase (Decrease) of Short-Term Debt',     category: 'D' },
  { code: '7412',     cname: '應付短期票券增〈減〉',     ename: 'Increase (Decrease)  of Long-Term Debt',     category: 'D' },
  { code: '7430',     cname: '避險之衍生金融商品增減─CFF',     ename: 'Hedging Derivative Financial Instruments CFF',     category: 'D' },
  { code: '7431',     cname: '透過損益按公允價值衡量之金融商品增〈減〉CFF',     ename: 'Increase(Decrease) in Financial Liabilities at FVPL (CFF)',     category: 'D' },
  { code: '7432',     cname: '其他金融負債增〈減〉CFF',     ename: 'Increase(Decrease) in Other Financial Liabilities (CFF)',     category: 'D' },
  { code: '7441',     cname: '舉借長期借款',     ename: 'Increase in Long-term Debt',     category: 'D' },
  { code: '7442',     cname: '償還長期借款',     ename: 'Long-term Debt Redeemed',     category: 'D' },
  { code: '7443',     cname: '發行公司債',     ename: 'Proceeds from issuing bonds',     category: 'D' },
  { code: '7444',     cname: '償還公司債',     ename: 'Repayments of bonds',     category: 'D' },
  { code: '7445',     cname: '現金增 〈減〉 資',     ename: 'Proceeds from Capital Increase(Decrease)',     category: 'D' },
  { code: '7446',     cname: '庫藏股票減〈增〉',     ename: 'Decrease(Increase) - Treasure Stocks',     category: 'D' },
  { code: '7447',     cname: '行使員工認股權',     ename: 'Execution of Employee Stock Option',     category: 'D' },
  { code: '7448',     cname: '發行特別股負債',     ename: 'Proceeds from issuing preference share liabilities',     category: 'D' },
  { code: '7449',     cname: '償還長特別股負債',     ename: 'Repayments of preference share liabilities',     category: 'D' },
  { code: '744A',     cname: '取得子公司股權CFF',     ename: 'Acquisition of ownership interests in subsidiaries',     category: 'D' },
  { code: '744B',     cname: '處分子公司股權CFF',     ename: 'Disposal of ownership interests in subsidiaries (without losing control)',     category: 'D' },
  { code: '744D',     cname: '金融資產證券化款項-CFF',     ename: 'Proceeds from financial assets securitization-CFF',     category: 'D' },
  { code: '744E',     cname: '短期借款增加',     ename: 'Increase in short-term loans',     category: 'D' },
  { code: '744F',     cname: '應付商業本票增加',     ename: 'Increase in commercial papers payable',     category: 'D' },
  { code: '744G',     cname: '成本衡量金負增加-CFF',     ename: 'Increase in financial liabilities at cost-CFF',     category: 'D' },
  { code: '744H',     cname: '短期借款減少',     ename: 'Decrease in short-term loans',     category: 'D' },
  { code: '744I',     cname: '應付商業本票減少',     ename: 'Decrease in commercial papers payable',     category: 'D' },
  { code: '744J',     cname: '成本衡量金負減少-CFF',     ename: 'Decrease in financial liabilities at cost-CFF',     category: 'D' },
  { code: '7460',     cname: '退還(支付)所得稅CFF',     ename: 'Income taxes refund (paid)-CFF',     category: 'D' },
  { code: '7470',     cname: '非控制權益增〈減〉',     ename: 'Change in non-controlling interests',     category: 'D' },
  { code: '749B',     cname: 'CFF─調整項(出貨)',     ename: 'Other Adjustment -Financing Activities',     category: 'D' },
  { code: '74AB',     cname: '處分子公司股權CFF',     ename: 'Disposal of ownership interests in subsidiaries (without losing control)',     category: 'D' },
  { code: '7501',     cname: '存出保證金(增)減',     ename: 'Decrease (increase) in guarantee deposits paid',     category: 'D' },
  { code: '7502',     cname: '存出再保責任準備金(增)減',     ename: 'Decrease (increase) in reinsurance liability reserve contributed',     category: 'D' },
  { code: '7503',     cname: '應付再保賠款與給付增(減)',     ename: 'Increase (decrease) in reinsurance indemnity payable',     category: 'D' },
  { code: '7504',     cname: '存入保證金增(減)',     ename: 'Increase (decrease) in refundable deposit',     category: 'D' },
  { code: '7505',     cname: '存入再保責任準備金增(減)',     ename: 'Increase (decrease) in reinsurance liability reserve received',     category: 'D' },
  { code: '7510',     cname: '支付員工退休金',     ename: 'Employee Pension Payment',     category: 'D' },
  { code: '7511',     cname: '應收帳款〈增〉減',     ename: 'Decrease (Increase) in Accounts Receivable',     category: 'D' },
  { code: '7512',     cname: '應付帳款增〈減〉',     ename: 'Increase(Decrease) in Accounts Payable',     category: 'D' },
  { code: '7513',     cname: '呆帳損失增 〈減〉',     ename: 'Provision (reversal of provision) for bad debt expense',     category: 'D' },
  { code: '7521',     cname: '其他應收帳款〈增〉減',     ename: 'Decrease (Increase) in Other Accounts Receivable',     category: 'D' },
  { code: '7531',     cname: '存貨〈增〉減',     ename: 'Decrease (increase) in inventories',     category: 'D' },
  { code: '7532',     cname: '存貨跌價損失增 (減)',     ename: 'Increase (Decrease) in inventory falling price losses',     category: 'D' },
  { code: '7533',     cname: '存貨盤 (盈) 虧及報廢',     ename: 'Inventory losses (surplus) and loss on disposal of inventory',     category: 'D' },
  { code: '7543',     cname: '應收保費(增)減',     ename: 'Decrease (increase) in premiums receivable',     category: 'D' },
  { code: '7544',     cname: '應付佣金增 (減)',     ename: 'Increase (decrease) in commissions payable',     category: 'D' },
  { code: '7546',     cname: '負債準備增〈減〉CFO',     ename: 'Increase (decrease) in provisions',     category: 'D' },
  { code: '7560',     cname: '無形資產〈增〉減',     ename: 'Decrease(Increase) in Intangible Assets',     category: 'D' },
  { code: '7561',     cname: '應攤回再保賠(增)減',     ename: 'Decrease (Increase) Reinsurance Receivable',     category: 'D' },
  { code: '7562',     cname: '應付保險賠款增(減)',     ename: 'Increase (decrease) in claims payable',     category: 'D' },
  { code: '7564',     cname: '不良債權變現數',     ename: 'Non-Performing Loan Sold',     category: 'D' },
  { code: '7565',     cname: '應收再保業務款(增)減',     ename: '(Increase)Decrease Obligatory Reinsurance Receivable',     category: 'D' },
  { code: '7566',     cname: '應付再保業務款增 (減)',     ename: 'Increase (decrease) in due to reinsurers and ceding companies',     category: 'D' },
  { code: '7568',     cname: '再保險合約資產(增)減CFO',     ename: 'Decrease (increase) in reinsurance assets-CFO',     category: 'D' },
  { code: '7611',     cname: '支付現金股利',     ename: 'Cash dividends paid',     category: 'D' },
  { code: '7700',     cname: '匯率影響數',     ename: 'Effect of exchange rate changes on cash and cash equivalents',     category: 'D' },
  { code: '7712',     cname: '支付利息CFF',     ename: 'Interest paid',     category: 'D' },
  { code: '7713',     cname: '支付股利─CFO',     ename: 'Dividends paid',     category: 'D' },
  { code: '7714',     cname: '支付利息─CFO',     ename: 'Interest paid -CFO',     category: 'D' },
  { code: '7721',     cname: '退還(支付)所得稅─CFO',     ename: 'Income taxes refund (paid) -CFO',     category: 'D' },
  { code: '7800',     cname: '本期產生現金流量',     ename: 'Cash Flows during Current Period',     category: 'D' },
  { code: '7910',     cname: '期初現金及約當現金',     ename: 'Cash and cash equivalents at beginning of period',     category: 'D' },
  { code: '7911',     cname: 'IAS7現金定義附賣回票債券',     ename: 'Securities purchased under resell agreements qualifying for cash &cash eq.-IAS 7',     category: 'D' },
  { code: '7917',     cname: '資產負債表帳列現金',     ename: 'Cash and cash equivalents reported in the statement of financial position',     category: 'D' },
  { code: '7918',     cname: '其他符合國際會計準則第七號現金及約當現金定義之項目',     ename: 'Other items qualifying for cash and cash equivalents under the definition ofIAS7',     category: 'D' },
  { code: '7919',     cname: 'IAS7現金定義- 存拆同業',     ename: 'Due fm the CB & call loans to banks qualifying for cash & cash equivalents-IAS 7',     category: 'D' },
  { code: '7920',     cname: '期末現金及約當現金',     ename: 'Cash and cash equivalents at end of period',     category: 'D' },
  { code: 'K632',     cname: '季底售貨天數',     ename: 'Inventory Turnover Days_Quarter end',     category: 'X' },
  { code: 'MV',       cname: '季底普通股市值',     ename: 'Market Value of Common Stocks at Quarter-End',     category: 'Z' },
  { code: 'R100',     cname: 'ROA(C)稅前息前折舊前',     ename: 'Return on Assets Ratio (C) - Recurring Income Before Interes',     category: 'S' },
  { code: 'R101',     cname: 'ROA(A)稅後息前',     ename: 'Return on Assets Ratio (A) - Income from Continuing Operatio',     category: 'S' },
  { code: 'R102',     cname: 'ROA(B)稅後息前折舊前',     ename: 'Return on Assets Ratio (B) - Recurring Income Before Interes',     category: 'S' },
  { code: 'R103',     cname: 'ROE(A)─稅後',     ename: 'Return on Equity - After Tax',     category: 'S' },
  { code: 'R104',     cname: 'ROE(B)─常續利益',     ename: 'ROE - Recurring Income',     category: 'S' },
  { code: 'R105',     cname: '營業毛利率',     ename: 'Gross Margin Ratio',     category: 'S' },
  { code: 'R106',     cname: '營業利益率',     ename: 'Operating Income Ratio',     category: 'S' },
  { code: 'R107',     cname: '稅前淨利率',     ename: 'Pre-Tax Income Ratio',     category: 'S' },
  { code: 'R108',     cname: '稅後淨利率',     ename: 'Net Income Ratio',     category: 'S' },
  { code: 'R10P',     cname: '營業毛利率TSE',     ename: 'Gross Margin % TSE',     category: 'Z' },
  { code: 'R10Q',     cname: '營業利益率TSE',     ename: 'Operating Income % TSE',     category: 'Z' },
  { code: 'R10R',     cname: '稅前淨利率TSE',     ename: 'Pre-Tax Income % TSE',     category: 'Z' },
  { code: 'R112',     cname: '業外收支 /營收',     ename: 'Net Non-Operating Income Ratio',     category: 'S' },
  { code: 'R11A',     cname: '(稅前純益+提列放款備抵呆帳)/平均淨值',     ename: '(Pre-Tax Income + Loan Alowances) /Average Equity',     category: '' },
  { code: 'R11C',     cname: '(稅前純益+提列放款備抵呆帳)/平均資產',     ename: '(Pre-Tax Income + Loan Alowances) /Average Assets',     category: '' },
  { code: 'R11D',     cname: '利息淨收益 /稅前純益',     ename: 'Net Interest Income /Pre-Tax Income',     category: '' },
  { code: 'R11E',     cname: '稅前純益 /淨收益',     ename: 'Pre-Tax Income /Net Revernue',     category: '' },
  { code: 'R11F',     cname: '稅前純益 /員工人數',     ename: 'Pre-Tax Income /Employees',     category: '' },
  { code: 'R11G',     cname: '可轉讓定存單 /定存',     ename: 'Negotiable Certificate of Deposite /Periodic Deposit',     category: '' },
  { code: 'R11H',     cname: '新台幣資產與負債 180天到期累計缺口 /淨值(母公司)',     ename: 'Accumulated Gap of NTD Asset & Liability due to 180 days /Equity(Parent Company)',     category: '' },
  { code: 'R11I',     cname: '(一年內)利率敏感性資產 /利率敏感性負債(母公司)',     ename: 'Assets /Liabilities--Interest Rate Sensitive (1 Year)(Parent Company)',     category: '' },
  { code: 'R11J',     cname: '(一年內)利率敏感性缺口 /淨值(母公司)',     ename: 'Interest Rate Sensitive Gap /Equity (1 Year)(Parent Company)',     category: '' },
  { code: 'R11K',     cname: '投資成長率(母公司)',     ename: 'Growth Rate of Investment(Parent Company)',     category: '' },
  { code: 'R11L',     cname: '保證成長率(母公司)',     ename: 'Growth Rate of Guarantee(Parent Company)',     category: '' },
  { code: 'R11U',     cname: 'ROE─綜合損益',     ename: 'ROE-Comprehensive Income',     category: 'S' },
  { code: 'R11V',     cname: 'ROA─綜合損益',     ename: 'ROA-Comprehensive Income',     category: 'S' },
  { code: 'R120',     cname: '放款平均利率_母公司',     ename: 'Average Interest Income of Loans (Parent Company)',     category: '' },
  { code: 'R121',     cname: '存放款利差(NIS)_母公司',     ename: 'Net Interest Spread (NIS)_Parent Company',     category: '' },
  { code: 'R122',     cname: '收支比率',     ename: 'Ratio Of Revenue Divided By Expense',     category: '' },
  { code: 'R128',     cname: '放款 /存款',     ename: 'Loans to Deposit Ratio -B',     category: '' },
  { code: 'R12E',     cname: '淨利息收益率(NIM)_母公司',     ename: 'Net Interest Margin (NIM)_Parent Company',     category: '' },
  { code: 'R145',     cname: '稅前息前折舊前淨利率',     ename: 'Net Profit Margin - Before Interest, Taxes, Depreciation and',     category: 'S' },
  { code: 'R146',     cname: '已實現銷貨毛利率',     ename: 'Realized Gross Margin Ratio',     category: 'S' },
  { code: 'R165',     cname: '股利殖利率',     ename: 'Dividend Yield',     category: 'Z' },
  { code: 'R166',     cname: '現金股利率',     ename: 'Cash Dividend Yield',     category: 'Z' },
  { code: 'R16A',     cname: '股利支付率',     ename: 'Dividend Payout Ratio',     category: 'W' },
  { code: 'R179',     cname: '貝里比率',     ename: 'Berry Ratio',     category: 'S' },
  { code: 'R180',     cname: '營業資產報酬率',     ename: 'Return on Operating Assets',     category: 'S' },
  { code: 'R181',     cname: '各項準備金對業主權益比率- 產險',     ename: 'Total Reserves/ Equity %',     category: '' },
  { code: 'R182',     cname: '特別準備金對業主權益比率',     ename: 'Special Claim Reserves/ Equity %',     category: '' },
  { code: 'R183',     cname: '關係企業投資額對業主權益比率- 壽險',     ename: 'Investment of Relative Enterprise / Equity % -Life Insurance',     category: '' },
  { code: 'R184',     cname: '新契約費用率- 壽險',     ename: 'New Contract Expense % -Life Insurance',     category: '' },
  { code: 'R185',     cname: '保費收入變動率',     ename: 'Change Rate of Direct Premiums',     category: '' },
  { code: 'R186',     cname: '資金運用比率- 壽險',     ename: 'Capital Application Rate -Life Insurance',     category: '' },
  { code: 'R187',     cname: '繼續率- 13個月- 壽險',     ename: 'Continue Rate- Thirteen Months -Life Insurance',     category: '' },
  { code: 'R188',     cname: '繼續率- 25個月- 壽險',     ename: 'Continue Rate- Twenty-Five Months -Life Insurance',     category: '' },
  { code: 'R189',     cname: '資金運用收益率- 壽險',     ename: 'Return on Usable Capital',     category: '' },
  { code: 'R191',     cname: '自留簽單保費對業主權益比率- 產險',     ename: 'Net Premium/ Equity % -Property Insurance',     category: '' },
  { code: 'R192',     cname: '毛保費對業主權益比率- 產險',     ename: 'Gross Premium/ Equity %',     category: '' },
  { code: 'R193',     cname: '賠款及特別準備金對業主權益比率',     ename: 'Indemnity & Special Claim Reserve / Equity %',     category: '' },
  { code: 'R194',     cname: '自留綜合率- 產險- 年底',     ename: 'Combined Ratio-Property Insurance',     category: '' },
  { code: 'R195',     cname: '自留費用率- 產險',     ename: 'Rate of Retentive Expense -Property Insurance',     category: '' },
  { code: 'R196',     cname: '自留滿期損失率- 產險',     ename: 'Loss Ratio-Property Insurance',     category: '' },
  { code: 'R197',     cname: '各種責任準備金對資產比率',     ename: 'Operating Reserves / Total Assets % -seasonly',     category: '' },
  { code: 'R198',     cname: '各種責任準備金年變動率',     ename: 'Change Rate of Operating Reserves',     category: '' },
  { code: 'R19A',     cname: '自留滿期損失率(含IBNR)',     ename: 'Loss Ratio (IBNR Included)',     category: '' },
  { code: 'R200',     cname: '費用率- 產險',     ename: 'Expense Ratio -Property Insurance',     category: '' },
  { code: 'R201',     cname: '營業費用率',     ename: 'Operating Expenses Ratio',     category: 'T' },
  { code: 'R202',     cname: '用人費用率',     ename: 'Labor Cost Ratio',     category: 'T' },
  { code: 'R203',     cname: '研究發展費用率',     ename: 'R&D Expenses Ratio',     category: 'T' },
  { code: 'R204',     cname: '呆帳費用率',     ename: 'Bad Debts Expense Ratio',     category: 'T' },
  { code: 'R205',     cname: '現金流量比率',     ename: 'Cash Flow Ratio',     category: 'T' },
  { code: 'R206',     cname: '有息負債利率',     ename: 'Cost of Interest-Bearing Debt',     category: 'T' },
  { code: 'R207',     cname: '稅率 (A)',     ename: 'Tax Rate (A)',     category: 'T' },
  { code: 'R208',     cname: '現金流量允當%',     ename: 'Cash Flow Adequacy Ratio',     category: 'W' },
  { code: 'R209',     cname: '現金再投資%',     ename: 'Cash Reinvestment Ratio',     category: 'W' },
  { code: 'R212',     cname: '初年度保費比率- 壽險',     ename: 'First-year Premium Ratio -Life Insurance',     category: '' },
  { code: 'R213',     cname: '續年度保費比率- 壽險',     ename: 'Non-first-year Premium Ratio -Life Insurance',     category: '' },
  { code: 'R214',     cname: '投資報酬率',     ename: 'Return on Investment %',     category: '' },
  { code: 'R215',     cname: '不動產投資與不動產抵押放款對資產比率- 壽險',     ename: 'Investment & Loan of Real estate / Total Assets % -Life Insurance',     category: '' },
  { code: 'R216',     cname: '直接保費收入變動率(季)- 產險',     ename: 'Change Rate of Direct Premiums- seasonly -Property Insurance',     category: '' },
  { code: 'R217',     cname: '直接已付賠款變動率(季)- 產險',     ename: 'Change Rate of Indemnities- seasonly -Property Insurance',     category: '' },
  { code: 'R218',     cname: '自留保費變動率(季)- 產險',     ename: 'Growth Rate of Retention Premium Earned-YOY',     category: '' },
  { code: 'R219',     cname: '淨再保佣金對業主權益影響率- 產險',     ename: 'Net Reinsurance Commission/ Equity % -Property Insurance',     category: '' },
  { code: 'R220',     cname: '應收利息 /放款',     ename: 'Interest Receivables/Loans',     category: '' },
  { code: 'R221',     cname: '備抵呆帳 /放款',     ename: 'Allowance for Bad Debt /Loans',     category: '' },
  { code: 'R222',     cname: '金融業務成本率',     ename: 'Gross Interest Expense/Total Revenue',     category: '' },
  { code: 'R228',     cname: '存借款平均利率_母公司',     ename: 'Average Interest Expense of Deposit & Loan (Parent Company)',     category: '' },
  { code: 'R241',     cname: '違約金損失率',     ename: 'Contract Loss Rate',     category: '' },
  { code: 'R242',     cname: '買賣損失率',     ename: 'Trading Loss Rate',     category: '' },
  { code: 'R243',     cname: '錯帳損失率',     ename: 'Error Booking Loss Rate',     category: '' },
  { code: 'R248',     cname: '現金流量允當比率',     ename: 'Ratio of Cash Flow Adequacy',     category: '' },
  { code: 'R252',     cname: '稅率 (B)%',     ename: 'Tax Rate (B)',     category: 'T' },
  { code: 'R302',     cname: '每股淨值 (B)',     ename: 'Book Value Per Share (B) - Reserve for Capital Increase Adju',     category: 'U' },
  { code: 'R303',     cname: '每股現金流量',     ename: 'Cash Flow Per Share',     category: 'U' },
  { code: 'R304',     cname: '每股營業額(元)',     ename: 'Sales Per Share',     category: 'U' },
  { code: 'R305',     cname: '每股營業利益(元)',     ename: 'Operating Income Per Share',     category: 'U' },
  { code: 'R306',     cname: '每股稅前淨利(元)',     ename: 'Pre-Tax Income Per Share',     category: 'U' },
  { code: 'R307',     cname: '每股淨值 (A)',     ename: 'Book Value Per Share (A) - Reserve for Capital Increase and',     category: 'U' },
  { code: 'R308',     cname: '每股淨值 (C)',     ename: 'Book Value Per Share (C) - Preferred Stocks Adjusted',     category: 'U' },
  { code: 'R314',     cname: '每股綜合損益',     ename: 'Comprehensive Income Per Share',     category: 'U' },
  { code: 'R315',     cname: '季底每股稅前淨利(元)',     ename: 'Pre-Tax Income Per Share',     category: 'U' },
  { code: 'R316',     cname: '季底每股稅後淨利(元)',     ename: 'Net Income Per Share',     category: 'U' },
  { code: 'R401',     cname: '營收成長率',     ename: 'Net Operating Revenue Growth Rate - YOY',     category: 'V' },
  { code: 'R402',     cname: '營業毛利成長率',     ename: 'Gross Operating Profit Growth Rate - YOY',     category: 'V' },
  { code: 'R403',     cname: '營業利益成長率',     ename: 'Operating Income Growth Rate - YOY',     category: 'V' },
  { code: 'R404',     cname: '稅前淨利成長率',     ename: 'Pre-Tax Income Growth Rate - YOY',     category: 'V' },
  { code: 'R405',     cname: '稅後淨利成長率',     ename: 'Net Income Growth Rate - YOY',     category: 'V' },
  { code: 'R406',     cname: '經常淨利成長率',     ename: 'Income from Continuing Operations Growth Rate - YOY',     category: 'V' },
  { code: 'R408',     cname: '總資產成長率',     ename: 'Total Assets Growth Rate - YOY',     category: 'V' },
  { code: 'R409',     cname: '淨值成長率',     ename: 'Total Equity Growth Rate - YOY',     category: 'V' },
  { code: 'R40E',     cname: '保費收入成長率',     ename: 'Growth Rate of Direct Premiums',     category: '' },
  { code: 'R40F',     cname: '簽單保費收入成長率',     ename: 'Growth Rate of Direct Written Premiums',     category: '' },
  { code: 'R40G',     cname: '自留滿期保費收入成長率',     ename: 'Growth Rate of Net Retention Premiums Earned',     category: '' },
  { code: 'R40H',     cname: '簽單保費收入變動率',     ename: 'Change Rate of Direct Written Premiums',     category: '' },
  { code: 'R40I',     cname: '自留滿期保費收入變動率',     ename: 'Change Rate of Net Retion Premiums Earned',     category: '' },
  { code: 'R410',     cname: '折舊性FA成長率',     ename: 'Depreciable Fixed Assets Growth Rate - YOY',     category: 'V' },
  { code: 'R411',     cname: '總資產報酬成長率',     ename: 'Return on Total Assets Growth Rate - YOY',     category: 'V' },
  { code: 'R420',     cname: '已實現銷貨毛利成長率',     ename: 'Realized Gross Operating Profit Growth Rate - YOY',     category: 'V' },
  { code: 'R422',     cname: '內部保留比率',     ename: 'Retention Ratio',     category: 'W' },
  { code: 'R431',     cname: '營收變動率',     ename: 'Net Operating Revenue Growth Rate - QOQ',     category: 'V' },
  { code: 'R432',     cname: '營業利益變動率',     ename: 'Operating Income Growth Rate - QOQ',     category: 'V' },
  { code: 'R433',     cname: '淨利變動率(單季)',     ename: 'Net Income Growth Rate - QOQ',     category: 'V' },
  { code: 'R434',     cname: '稅前盈餘變動率',     ename: 'Pre-Tax Income Growth Rate - QOQ',     category: 'V' },
  { code: 'R501',     cname: '流動比率',     ename: 'Current Ratio',     category: 'W' },
  { code: 'R502',     cname: '速動比率',     ename: 'Acid-Test Ratio',     category: 'W' },
  { code: 'R503',     cname: '利息支出率',     ename: 'Interest Expense Ratio',     category: 'W' },
  { code: 'R504',     cname: '總負債/ 總淨值',     ename: 'Liabilities /Equity Ratio',     category: 'W' },
  { code: 'R505',     cname: '負債比率％',     ename: 'Liabilities Ratio',     category: 'W' },
  { code: 'R506',     cname: '淨值 / 資產',     ename: 'Equity /Total Assets Ratio',     category: 'W' },
  { code: 'R507',     cname: '長期資金適合率 (A)',     ename: '(Long-Term Liabilities +Equity) /Fixed Assets Ratio',     category: 'W' },
  { code: 'R509',     cname: '借款依存度',     ename: 'Debt /Equity Ratio',     category: 'W' },
  { code: 'R50J',     cname: '速動比率TSE',     ename: 'Acid Test TSE',     category: 'Z' },
  { code: 'R511',     cname: '或有負債 / 淨值',     ename: 'Contingent Liabilities /Equity Ratio',     category: 'W' },
  { code: 'R512',     cname: '利息保障倍數',     ename: 'Times Interest Earned',     category: '' },
  { code: 'R513',     cname: '營業利益 /實收資本比',     ename: 'Operating Income Per Shares',     category: '' },
  { code: 'R514',     cname: '稅前純益 /實收資本',     ename: 'Pre-Tax Income /Capital',     category: '' },
  { code: 'R517',     cname: '利息支出率(B)',     ename: 'Interest Expense-to-Sales %',     category: 'W' },
  { code: 'R524',     cname: '存款 /淨值 (倍)',     ename: 'Deposit /Shareholders\' Equity',     category: '' },
  { code: 'R531',     cname: '常續性稅後淨利',     ename: 'Recurring Net Income',     category: 'B' },
  { code: 'R532',     cname: '常續利益率--稅後',     ename: 'Recurring Income Ratio (After Tax)',     category: 'S' },
  { code: 'R534',     cname: '常續淨利成長率',     ename: 'Recurring Net Income Growth Rate - YOY',     category: 'V' },
  { code: 'R535',     cname: '常續性EPS',     ename: 'Recurring EPS',     category: 'U' },
  { code: 'R536',     cname: '當季季底P/E',     ename: 'P/E Ratio at Quarter-End',     category: 'Z' },
  { code: 'R537',     cname: '當季季底P/B',     ename: 'P/B Ratio at Quarter-End',     category: 'Z' },
  { code: 'R53B',     cname: 'Tobins Q',     ename: 'Tobins Q',     category: 'Z' },
  { code: 'R53C',     cname: 'Tobins Q (A)',     ename: 'Tobins Q (A)',     category: 'Z' },
  { code: 'R549',     cname: '當季季底 PSR',     ename: 'P/S Ratio at Quarter-End',     category: 'Z' },
  { code: 'R54A',     cname: '資產市占率',     ename: 'Market Share of Assets',     category: '' },
  { code: 'R54B',     cname: '淨值市占率',     ename: 'Market Share of Net Worth',     category: '' },
  { code: 'R54C',     cname: '存款市占率',     ename: 'Market Share of Deposits',     category: '' },
  { code: 'R54D',     cname: '放款市占率',     ename: 'Market Share of Loans',     category: '' },
  { code: 'R606',     cname: '存貨及應收帳款  / 淨值',     ename: '(Inventories +Accounts Receivable) /Equity Ratio',     category: 'X' },
  { code: 'R607',     cname: '總資產週轉次數',     ename: 'Total Asset Turnover',     category: 'X' },
  { code: 'R608',     cname: '應收帳款週轉次',     ename: 'Accounts Receivable Turnover',     category: 'X' },
  { code: 'R609',     cname: '平均收帳天數',     ename: 'Days Sales Outstanding',     category: 'X' },
  { code: 'R60I',     cname: '季底應收帳款/營收 TSE',     ename: 'End Accounts Receivable /Sales TSE',     category: 'Z' },
  { code: 'R60J',     cname: '季底存貨/營收 TSE',     ename: 'End Inventory /Sales TSE',     category: 'Z' },
  { code: 'R60K',     cname: '平均收帳天數 TSE',     ename: 'Days Receivables Outstanding',     category: 'Z' },
  { code: 'R60L',     cname: '平均售貨天數 TSE',     ename: 'Days Inventory Outstanding',     category: 'Z' },
  { code: 'R610',     cname: '存貨週轉率 (次)',     ename: 'Inventory Turnover',     category: 'X' },
  { code: 'R611',     cname: '平均售貨天數',     ename: 'Days Inventory on Hand',     category: 'X' },
  { code: 'R612',     cname: '固定資產週轉次數',     ename: 'Fixed Asset Turnover',     category: 'X' },
  { code: 'R613',     cname: '淨值週轉率 (次)',     ename: 'Equity Turnover',     category: 'X' },
  { code: 'R614',     cname: '應付帳款付現天數',     ename: 'Days Payable Outstanding',     category: 'X' },
  { code: 'R615',     cname: '淨營業週期 (日)',     ename: 'Net Operating Cycle',     category: 'X' },
  { code: 'R624',     cname: '土地 /淨值',     ename: 'Land Hold/Shareholders\' Equity',     category: '' },
  { code: 'R625',     cname: '固定資產 /淨值',     ename: 'Fixed Assets/Shareholders\' Equity',     category: '' },
  { code: 'R627',     cname: '催收款比率',     ename: 'Ratio of Non-accrual Loans',     category: '' },
  { code: 'R628',     cname: '利息未收現比率',     ename: 'Percentage Of Interest Receivable Over Interest Revenue',     category: '' },
  { code: 'R631',     cname: '季底收款天數',     ename: 'Accounts receivables Turnover Days_Quarter end',     category: 'X' },
  { code: 'R63B',     cname: '季底(應收帳款/營收)',     ename: 'A/R /Net Sale',     category: '' },
  { code: 'R640',     cname: '近四季固定資產週轉率',     ename: 'Fixed Asset Turnover- Lately 4 quarters',     category: '' },
  { code: 'R678',     cname: '營運資金',     ename: 'Working Capital',     category: 'W' },
  { code: 'R69B',     cname: '自由現金流量 (D)',     ename: 'Free Cash Flow (D)',     category: 'X' },
  { code: 'R721',     cname: '流動準備比率(母公司)',     ename: 'Liquidity Ratio(Parent Company)',     category: '' },
  { code: 'R722',     cname: '存放比率(母公司)',     ename: 'Loans to Deposit Ratio(Parent Company)',     category: '' },
  { code: 'R723',     cname: '狹義逾放比率',     ename: 'NPL Ratio(A)',     category: '' },
  { code: 'R724',     cname: '利息支出占年均存款餘額比',     ename: 'Interest Expense/Average Deposit',     category: '' },
  { code: 'R725',     cname: '利息收入占年均放款餘額比',     ename: 'Interest Income/Loans',     category: '' },
  { code: 'R732',     cname: '資本適足率 (BIS)',     ename: 'Capital Adequacy Ratio',     category: '' },
  { code: 'R831',     cname: '每人放款',     ename: 'Loans Per Employee',     category: '' },
  { code: 'R832',     cname: '每人利息收入',     ename: 'Interest Income Per Employee',     category: '' },
  { code: 'R833',     cname: '每人保費收入',     ename: 'Direct Premiums Per Employee',     category: '' },
  { code: 'R834',     cname: '每人營收',     ename: 'Revenue Per Employee',     category: 'Z' },
  { code: 'R835',     cname: '每人營業利益',     ename: 'Operation Income Per Employee',     category: 'Z' },
  { code: 'R836',     cname: '每人配備率',     ename: 'Fixed Assets Per Employee',     category: 'Z' },
  { code: 'W34W',     cname: '業外─其他利益及損失─其他',     ename: 'Non-Operating - Other Gain/Loss - Other',     category: 'B' },
  { code: 'W39G',     cname: '代收款增(減)',     ename: 'Increase (decrease) in receipts under custody',     category: 'D' } 
];

var StatementCodeSchema = new Schema({
    code : String,
    category : String,
    name: String,
    ename: String
}, { collection : 'statement_code' });

StatementCodeSchema.index({code: 1}, {unique: true});

StatementCodeSchema.statics = {

    initDb : function(){
        var self = this;
        return Promise.delay(100).then(function(){
            _.each(codeList, function(fields) {
                self.update({
                    code: fields.code
                }, {
                    $set: {
                        name: fields.cname,
                        ename: fields.ename,
                        category: fields.category
                    }
                }, {upsert: true}).exec();
            });
        });
    }

};

module.exports = StatementCodeSchema;
